=== Riverscapes/RiverscapesXML/RaveBusinesslogic/XSD/project_explorer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Overall Structure  -->
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Name"/>
        <xs:element type="xs:string" name="Description" minOccurs="0"/>
        <xs:element type="xs:string" name="ProjectType" minOccurs="1" maxOccurs="1"/>
        <xs:element type="NodeType" name="Node"/>
        <xs:element type="ViewsType" name="Views" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Allowable things to add to the map-->
  <xs:simpleType name="datatype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vector" />
      <xs:enumeration value="raster" />
      <xs:enumeration value="tile" />
      <xs:enumeration value="file" />
      <xs:enumeration value="tin" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Node: A one-off tree branch that has an xpath -->
  <xs:complexType name="NodeType">
    <xs:sequence>
      <xs:element type="xs:string" name="Tileservice" minOccurs="0"/>
      <xs:element type="ChildrenType" name="Children" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="optional"/>
    <xs:attribute type="datatype" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="symbology" use="optional"/>
    <xs:attribute type="xs:integer" name="transparency" use="optional" />
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>

  <!-- Repeaters: loop over xml node "arrays" -->
  <xs:complexType name="RepeaterType">
    <xs:sequence>
      <xs:choice>
        <xs:element type="NodeType" name="Node" maxOccurs="1"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="required"/>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!--Children is basically just a bucket that can contain nodes and repeaters-->
  <xs:complexType name="ChildrenType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="NodeType" name="Node" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element type="RepeaterType" name="Repeater" minOccurs="1" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!-- There can be one Views node that contains many views-->
  <xs:complexType name="ViewsType">
    <xs:sequence>
      <xs:element type="ViewType" name="View" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="default" use="optional"/>
  </xs:complexType>

  <!-- Each view is a sequence of layers-->
  <xs:complexType name="ViewType">
    <xs:sequence>
      <xs:element type="LayerType" name="Layer" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>

  <!-- Each layer refers to a node by id and determins if the layer should be turned "on" and visible in the map-->
  <xs:complexType name="LayerType">
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:boolean" name="visible" use="optional"/>
  </xs:complexType>
</xs:schema>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/pibo_riverscapes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
    <Name>PIBO and Riverscapes data for Clearwater</Name>
    <ProjectType>pibo_riverscapes</ProjectType>
    <Node xpathlabel="Name">
        <Children collapsed="false">
            <Node label="PIBO Points" xpath="Realizations/Realization/Datasets">
                <Children collapsed="true">
                    <Node label="Active Status" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="pibo_active_sym" id="pibo_active"/>
                    <Node label="Site Designation" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="sitedes_sym" id="pibo_sitedes"/>
                    <Node label="Land Use Intensity" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="iPC_LU_igo" id="lui"/>
                    <Node label="Riparian Condition" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="condition_igo_v2" id="rcat_condition"/>
                    <Node label="Riparian Conversion" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="Veg_conversion_igo" id="rcat_conversion"/>
                    <Node label="Existing Dam Capacity" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="capacity_sym" id="brat_capacity"/>
                    <Node label="Risk" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="risk_sym" id="brat_risk"/>
                    <Node label="Restoration and Conservation Opportunities" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="opportunity_sym" id="brat_opportunity"/>
                    <Node label="Confinement Ratio" xpath="Geopackage/Layers/Vector[@lyrName='PIBO_points']" type="point" symbology="conratio_sym" id="con_ratio"/>
                </Children>
            </Node>
            <Node label="VBET DGOs" xpath="Realizations/Realization/Datasets">
                <Children collapsed="true">
                    <Node label="VBET DGOs" xpath="Geopackage/Layers/Vector[@lyrName='vbet_dgos']" type="polygon" symbology="dgo_sym" id="dgos"/>
                </Children>
            </Node>
            <Node label="Watershed Boundary" xpath="Realizations/Realization/Datasets">
                <Children collapsed="true">
                    <Node label="HUC10" xpath="Geopackage/Layers/Vector[@lyrName='huc10']" type="polygon" symbology="huc10_sym" id="huc10"/>
                </Children>
            </Node>
            <Node label="Hillshade" xpath="Realizations/Realization/Datasets">
                <Children>
                    <Node label="Hillshade" xpath="Raster[@id='HILLSHADE']" type="raster" symbology="Hillshade" id="hs" />
                </Children>
            </Node>
        </Children>
    </Node>
    <Views default="PIBO_active">
        <View name="PIBO Active Status" id="PIBO_active">
            <Description>This view displays the monitoring activity status for each PIBO site</Description>
            <Layers>
                <Layer id="pibo_active"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>
            </Layers>
        </View>
        <View name="PIBO Site Designation" id="PIBO_sitedes">
            <Description>This view displays the site designation for each PIBO site</Description>
            <Layers>
                <Layer id="pibo_sitedes"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>
            </Layers>
        </View>
        <View name="Land Use Intensity" id="LUI">
            <Description>This view displays the land use intensity output of the Anthropogenic Context Model</Description>
            <Layers>
                <Layer id="lui"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>
            </Layers>
        </View>
        <View name="Riparian Condition" id="RCAT_condition">
            <Description>This view displays the riparian condition output of the RCAT model</Description>
            <Layers>
                <Layer id="rcat_condition"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>  
            </Layers>
        </View>
        <View name="Riparian Conversion" id="RCAT_conversion">
            <Description>This view displays the riparian conversion output of the RCAT model</Description>
            <Layers>
                <Layer id="rcat_conversion"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>  
            </Layers>
        </View>
        <View name="Existing Dam Capacity" id="BRAT_capacity">
            <Description>This view displays the existing dam capacity output of the BRAT model</Description>
            <Layers>
                <Layer id="brat_capacity"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>  
            </Layers>
        </View>
        <View name="Risk" id="BRAT_risk">
            <Description>This view displays the risk for undesirable dams output of the BRAT model</Description>
            <Layers>
                <Layer id="brat_risk"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>  
            </Layers>
        </View>
        <View name="Restoration and Conservation Opportunities" id="BRAT_opportunity">
            <Description>This view displays the restoration and conservation opportunities output of the BRAT model</Description>
            <Layers>
                <Layer id="brat_opportunity"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>  
            </Layers>
        </View>
        <View name="Confinement Ratio" id="CON_ratio">
            <Description>This view displays the confinement ratio output of the confinement model</Description>
            <Layers>
                <Layer id="con_ratio"/>
                <Layer id="dgos"/>
                <Layer id="huc10"/>
                <Layer id="hs"/>  
            </Layers>
        </View>
    </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/RSContextNZ.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <!-- <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XSD/project_explorer.xsd"> -->
  <Name>Riverscapes Context</Name>
  <ProjectType>RSContext</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization">
    <Children collapsed="false">
      <Node label="Hydrography">
        <Children collapsed="false">
          <Node label="Hydrography">
            <Children collapsed="true">
              <Node label="Hydro Junctions" xpath="Datasets/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='junctions']" type="line" symbology="junctions" id="junctions" />
              <Node label="Perennial Drainage Network" xpath="Datasets/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='riverlines']" type="line" symbology="nhdperrenial" id="riverlines" />
              <Node label="Catchments" xpath="Datasets/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='catchments']" type="line" symbology="nhdperrenial" id="catchments" />
            </Children>
          </Node>
          <Node label="Watershed Boundaries">
            <Children collapsed="true">
              <Node label="Watersheds" xpath="Datasets/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='watersheds']" type="polygon" symbology="watesheds" />
            </Children>
          </Node>
        </Children>
      </Node>
      <Node label="Topography and Derivatives">
        <Children collapsed="true">
          <Node label="DEM (8 m)" xpath="Datasets/Raster[@id='DEM']" type="raster" symbology="dem" transparency="40" id="dem" />
          <Node label="Slope Analysis" xpath="Datasets/Raster[@id='SLOPE']" type="raster" symbology="slope" transparency="40" />
        </Children>
      </Node>
      <Node label="Hillshade">
        <Children collapsed="true">
          <Node xpathlabel="Name" xpath="Datasets/Raster[@id='HILLSHADE']" type="raster" symbology="hillshade" id="hs" />
        </Children>
      </Node>
      <Node label="Log File" xpath="Logs/LogFile" type="file" />
      <Node label="Metrics" xpath="Datasets/File" type="file" />
    </Children>
  </Node>
  <Views default="Default">
    <View name="Hydrology" id="Default">
      <Layers>
        <Layer id="riverlines" />
        <Layer id="hs" /> <!-- A test to see if we like it and to see if we avoid the webrave problem of green fill with HUC8-->
      </Layers>
    </View>
    <View name="Topography" id="Topography">
      <Layers>
        <Layer id="riverlines" />
        <Layer id="intermittent" />
        <Layer id="dem" />
        <Layer id="hs" />
      </Layers>
    </View>
  </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinesslogic/rca.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd">
	<Name>RCA</Name>
	<ProjectType>RCA</ProjectType>
	<Node xpathlabel="Name" xpath="Realizations/RSContext">
		<Children collapsed="false">
			<Node label="Inputs">
				<Children collapsed="true">
					<Node label="Vegetation">
						<Children>
							<Node label="Existing Vegetation">
								<Children collapsed="true">
									<Node label="Veg Type - EVT Type" xpath="Realizations/RCA/Inputs/Raster[@id='EXISTING_VEGETATION']" type="raster" symbology="Existing_Veg_EVT_Type" transparency="40" />
									<Node label="Veg Type - EVT Name" xpath="Realizations/RCA/Inputs/Raster[@id='EXISTING_VEGETATION']" type="raster" symbology="Existing_Veg_EVT_Name" transparency="40" />
									<Node label="Veg Type - EVT Class" xpath="Realizations/RCA/Inputs/Raster[@id='EXISTING_VEGETATION']" type="raster" symbology="Existing_Veg_EVT_Class" transparency="40" />
								</Children>
							</Node>
							<Node label="Historic Vegetation">
								<Children collapsed="true">
									<Node label="Veg Type - BPS Type" xpath="Realizations/RCA/Inputs/Raster[@id='HISTORIC_VEGETATION']" type="raster" symbology="Historic_Veg_BPS_Type" transparency="40" />
									<Node label="Veg Type - BPS Name" xpath="Realizations/RCA/Inputs/Raster[@id='HISTORIC_VEGETATION']" type="raster" symbology="Historic_Veg_BPS_Name" transparency="40" />
								</Children>
							</Node>
						</Children>
					</Node>
					<Node label="Network">
						<Children>
							<Node label="Network" xpath="Realizations/RCA/Inputs/Vector[@id='NHD_FLOWLINES']" type="vector" symbology="OldNetwork" />
							<Node label="Flow Direction" xpath="Realizations/RCA/Inputs/Vector[@id='NHD_FLOWLINES']" type="vector" symbology="FlowDirection" />
						</Children>
					</Node>
					<Node label="Fragmented Valley Bottom">
						<Children>
							<Node label="Valley Bottom Outline" xpath="Realizations/RCA/Inputs/Vector[@id='FRAGMENTED_VALLEY_BOTTOM']" type="vector" symbology="ValleyBottomOutline" />
							<Node label="Fragemented Valley Bottom" xpath="Realizations/RCA/Inputs/Vector[@id='FRAGMENTED_VALLEY_BOTTOM']" type="vector" symbology="FragmentedValleyBottom" />
						</Children>
					</Node>
					<Node label="Topography">
						<Children>
							<Node label="Flow Accumulation (Sqkm)" xpath="Realizations/RCA/Inputs/Raster[@id='FLOW_ACCUMULATION']" type="raster" symbology="flow_accumulation" transparency="40" />
							<Node label="DEM (10 m NED)" xpath="Realizations/RCA/Inputs/Raster[@id='NED_10M_DEM']" type="raster" symbology="dem" transparency="40" />
						</Children>
					</Node>
					<Node label="Large River Polygon" xpath="Realizations/RCA/Inputs/Vector[@id='LARGE_RIVER_POLYGON']" type="vector" symbology="LargeRiverPolygon" />
					<Node label="Precipitation" xpath="Realizations/RCA/Inputs/Raster[@id='PRECIPITATION']" type="raster" symbology="mean_annual_precip" transparency="40" />
				</Children>
			</Node>
			<Node label="Intermediates">
				<Children collapsed="true">
					<Node label="Bankfull Channel Intermediates">
						<Children>
							<Node label="Precipitation By Reach" xpath="Realizations/RCA/Outputs/Vector[@id='BANKFULL_WIDTHS_NETWORK']" type="vector" symbology="PrecipitationByReach" />
							<Node label="Upstream Drainage Area" xpath="Realizations/RCA/Intermediates/Vector[@id='BANKFULL_WIDTHS_NETWORK']" type="vector" symbology="upstreamdrainagearea" />
						</Children>
					</Node>
					<Node label="Confinement Intermediates">
						<Children>
							<Node label="Valley Bottom Width Polygons" xpath="Realizations/RCA/Intermediates/Vector[@id='VALLEY_BOTTOM_WIDTH']" type="vector" symbology="ValleyBottomWidthPolygons" />
							<Node label="Bankfull Channel Width Polygons" xpath="Realizations/RCA/Intermediates/Vector[@id='BANKFULL_CHANNEL_WIDTH']" type="vector" symbology="BankfullChannelWidthPolygons" />
						</Children>
					</Node>
					<Node label="Thiesessen Polygons">
						<Children>
							<Node label="Clipped Thiessen Polygons" xpath="Realizations/RCA/Intermediates/Vector[@id='CLIPPED_THIESSEN_POLYGONS']" type="vector" symbology="ClippedThiessenPolygons" />
						</Children>
					</Node>
					<Node label="RCA Intermediates">
						<Children>
							<Node label="Vegetated">
								<Children>
									<Node label="Vegetation Remaining" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_CONDITION_ASSESMENT']" type="vector" symbology="VegetationRemaining" />
									<Node label="Proportion Currently Vegetated" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_CONDITION_ASSESMENT']" type="vector" symbology="ProportionCurrentlyVegetated" />
									<Node label="Proportion Historically Vegetated" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_CONDITION_ASSESMENT']" type="vector" symbology="ProportionHistoricallyVegetated" />
								</Children>
							</Node>
							<Node label="Connectivity">
								<Children>
									<Node label="Floodplain Connectivity" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_CONDITION_ASSESMENT']" type="vector" symbology="FloodplainConnectivity" />
									<Node label="Floodplain Connectivity Raster" xpath="Realizations/RCA/Intermediates/Raster[@id='FLOODPLAIN_CONNECTIVITY']" type="raster" symbology="FloodplainConnectivityRaster" transparency="40" />
								</Children>
							</Node>
							<Node label="Land Use Intensity" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_CONDITION_ASSESMENT']" type="vector" symbology="LandUseIntensity" />
						</Children>
					</Node>
					<Node label="RVD Intermediates">
						<Children>
							<Node label="Riparian Corridor" xpath="Realizations/RCA/Intermediates/Raster[@id='RIPARIAN_CORRIDOR']" type="raster" symbology="RiparianCorridor" transparency="40" />
							<Node label="Riparian Conversion Raster" xpath="Realizations/RCA/Intermediates/Raster[@id='CONVERSION_RASTER']" type="raster" symbology="RiparianConversionType" transparency="40" />
						</Children>
					</Node>
				</Children>
			</Node>
			<Node label="Outputs">
				<Children collapsed="true">
					<Node label="Riparian Condition Assesment" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_CONDITION_ASSESMENT']" type="vector" symbology="RCA" />
					<Node label="Riparian Vegetation Departure">
						<Children>
							<Node label="Riparian Vegetation Departure" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_VEGETATION_DEPARTURE']" type="vector" symbology="RiparianVegetationDeparture" />
							<Node label="Riparian Conversion Type" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_VEGETATION_DEPARTURE']" type="vector" symbology="RiparianConversionType" />
							<Node label="Native Riparian Departure" xpath="Realizations/RCA/Outputs/Vector[@id='RIPARIAN_VEGETATION_DEPARTURE']" type="vector" symbology="NativeRiparianVegetationDeparture" />
						</Children>
					</Node>
					<Node label="Confinement">
						<Children>
							<Node label="Confinement Ratio" xpath="Realizations/RCA/Outputs/Vector[@id='CONFINEMENT_NETWORK']" type="vector" symbology="ConfinementRatio" />
						</Children>
					</Node>
					<Node label="Bankfull Channel">
						<Children>
							<Node label="Bankfull Channel Network" xpath="Realizations/RCA/Outputs/Vector[@id='BANKFULL_WIDTHS_NETWORK']" type="vector" symbology="BankfullChannelNetwork" />
							<Node label="Bankfull Channel Polygon" xpath="Realizations/RCA/Outputs/Vector[@id='BANKFULL_CHANNELL_POLYGON']" type="vector" symbology="BankfullChannelPolygon" />
						</Children>
					</Node>
				</Children>
			</Node>
		</Children>
	</Node>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/RSContextBC.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>Riverscapes Context</Name>
  <ProjectType>RSContextBC</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization">
    <Children collapsed="false">
      <Node label="Transportation Local">
        <Children collapsed="true">
          <Node xpathlabel="Name" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='dra_dgtl_road_atlas_mpar_sp']" type="line" id="roads" />
        </Children>
      </Node>
      <Node label="Hydrology">
        <Children collapsed="false">
				<Node label="Flow Lines" xpath="Datasets/Geopackage[@id='hydrology']/Layers/Vector[@lyrName='flow_lines']" type="line" id="flowlines"/>
				<Node label="Waterbodies" xpath="Datasets/Geopackage[@id='hydrology']/Layers/Vector[@lyrName='waterbodies']" type="polygon" id="waterbodies"/>
				<Node label="Watershed" xpath="Datasets/Geopackage[@id='hydrology']/Layers/Vector[@lyrName='watershed']" type="polygon" id="watershed"/>
        </Children>
      </Node>
      <Node label="Biogeoclimate">
        <Children collapsed="true">
          <Node xpathlabel="Name" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='bec_biogeoclimatic_poly']" type="polygon" id="biogeoclimatic"/>
        </Children>
      </Node>
	  <Node label="Vegetation">
		<Children collapsed="true">
			  <Node xpathlabel="Name" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='veg_comp_lyr_r1_poly']" type="polygon" id="veg_comp" />
		</Children>
	  </Node>
      <Node label="Topography and Derivatives">
        <Children collapsed="true">
          <Node label="DEM (10 m NED)" xpath="Datasets/DEM[@id='dem']" type="raster" symbology="dem" transparency="40" id="dem" />
          <Node label="Slope Analysis" xpath="Datasets/Raster[@id='SLOPE']" type="raster" symbology="slope" transparency="40" />
        </Children>
      </Node>
      <Node label="Hillshade">
        <Children collapsed="true">
          <Node xpathlabel="Name" xpath="Datasets/Raster[@id='hillshade']" type="raster" symbology="hillshade" id="hs" />
        </Children>
      </Node>
    </Children>
  </Node>
  <Views default="Default">
    <View name="Hydrology" id="Default">
      <Layers>
        <Layer id="flowlines" />
        <Layer id="waterbodies" />
        <Layer id="watershed" />
      </Layers>
    </View>
    <View name="Topography" id="Topography">
      <Layers>
        <Layer id="flowlines" />
        <Layer id="dem" />
        <Layer id="hs" />
      </Layers>
    </View>
    <View name="Transportation" id="Transportation">
      <Layers>
        <Layer id="roads" />
      </Layers>
    </View>
    <View name="Existing Vegetation" id="veg">
      <Layers>
        <Layer id="flowlines" />
        <Layer id="veg_comp" /> 
      </Layers>
    </View>
  </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/EC.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd"> -->
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XSD/project_explorer.xsd">
    <Name>Electrical Conductivity</Name>
    <ProjectType>EC</ProjectType>
    <Node xpathlabel="Name">
        <Children>
            <Repeater label="Realizations" xpath="Realizations/EC">
                <!-- this is a template for how each realization should render-->
                <Node xpathlabel="Name">
                    <Children collapsed="false">
                        <Node label="Inputs" xpath="Inputs">
                            <Children>
                                <Repeater label="Vectors" xpath="Vector">
                                    <Node xpathlabel="Name" xpath="Vector" type="line" symbology="" />
                                </Repeater>
                            </Children>
                        </Node>
                        <Node label="Analyses" xpath="Analyses">
                            <Children>
                                <Node label="Outputs" xpath="Analysis/Outputs">
                                    <Children>
                                        <Node xpathlabel="Name" xpath="Vector" type="line" symbology="Conductivity" />
                                    </Children>
                                </Node>
                            </Children>
                        </Node>
                    </Children>
                </Node>
            </Repeater>
        </Children>
    </Node>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/Hydro.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>CHaMP Delft3D Hydraulic Model</Name>
  <ProjectType>Hydro</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization">
    <Children collapsed="false">
      <Node label="Hydarulic Simulation(s)" xpath="Analyses/Analysis/Products">
        <Children collapsed="true">
          <Node label="Meta Data">
            <Children collapsed="true">
              <Node xpathlabel="Name" xpath="CSV[@id='metadata1']" type="file" />
              <Node xpathlabel="Name" xpath="CSV[@id='demgridresults1']" type="file" />
            </Children>
          </Node>
          <Node label="Outputs">
            <Children collapsed="false">
              <Node label="Water Depth" xpath="Raster[@id='Depth']" type="raster" symbology="wDepth" transparency="40" />
              <Node label="Velocity Magnitude" xpath="Raster[@id='Velocity_Magnitude']" type="raster" symbology="velocityMag" transparency="40" />
              <Node label="Velocity Vectors" xpath="Vector[@id='OUTPUTS_SHP']" type="line" symbology="velocityVec" />
              <Node label="Water Surface Elevation" xpath="Raster[@id='WSE']" type="raster" symbology="wsDEM" transparency="40" />
              <Node label="Flow Direction" xpath="Raster[@id='Direction']" type="raster" symbology="flowdir" transparency="40" />
              <Node label="Bed Elevation" xpath="Raster[@id='BedLevel']" type="raster" symbology="DEM" transparency="40" />
            </Children>
          </Node>
          <Node label="Validation Comparison">
            <Children>
              <Node label="Water Depth (model vs surveyed)" xpath="Raster[@id='WSE']" type="raster" symbology="depthError" transparency="40" />
            </Children>
          </Node>
        </Children>
      </Node>
    </Children>
  </Node>
</Project>
