=== Riverscapes/RiverscapesXML/RaveBusinesslogic/XSD/project_explorer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Overall Structure  -->
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Name"/>
        <xs:element type="xs:string" name="Description" minOccurs="0"/>
        <xs:element type="xs:string" name="ProjectType" minOccurs="1" maxOccurs="1"/>
        <xs:element type="NodeType" name="Node"/>
        <xs:element type="ViewsType" name="Views" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Allowable things to add to the map-->
  <xs:simpleType name="datatype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vector" />
      <xs:enumeration value="raster" />
      <xs:enumeration value="tile" />
      <xs:enumeration value="file" />
      <xs:enumeration value="tin" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Node: A one-off tree branch that has an xpath -->
  <xs:complexType name="NodeType">
    <xs:sequence>
      <xs:element type="xs:string" name="Tileservice" minOccurs="0"/>
      <xs:element type="ChildrenType" name="Children" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="optional"/>
    <xs:attribute type="datatype" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="symbology" use="optional"/>
    <xs:attribute type="xs:integer" name="transparency" use="optional" />
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>

  <!-- Repeaters: loop over xml node "arrays" -->
  <xs:complexType name="RepeaterType">
    <xs:sequence>
      <xs:choice>
        <xs:element type="NodeType" name="Node" maxOccurs="1"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="required"/>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!--Children is basically just a bucket that can contain nodes and repeaters-->
  <xs:complexType name="ChildrenType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="NodeType" name="Node" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element type="RepeaterType" name="Repeater" minOccurs="1" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!-- There can be one Views node that contains many views-->
  <xs:complexType name="ViewsType">
    <xs:sequence>
      <xs:element type="ViewType" name="View" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="default" use="optional"/>
  </xs:complexType>

  <!-- Each view is a sequence of layers-->
  <xs:complexType name="ViewType">
    <xs:sequence>
      <xs:element type="LayerType" name="Layer" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>

  <!-- Each layer refers to a node by id and determins if the layer should be turned "on" and visible in the map-->
  <xs:complexType name="LayerType">
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:boolean" name="visible" use="optional"/>
  </xs:complexType>
</xs:schema>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/Topo.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd">
  <!-- <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XSD/project_explorer.xsd"> -->
  <Name>CHaMP Topo</Name>
  <ProjectType>topo</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node label="Topos">
        <Children>
          <Node label="Auxiliary Survey Data" xpath="Realizations/Topography/TIN">
            <Children collapsed="true">
              <Node label="Channel Units">
                <Children>
                  <Node label="Unit ID" xpath="ChannelUnits" type="polygon" symbology="cu_UnitNum" />
                </Children>
              </Node>
              <Node label="Hawkins Channel Units">
                <Children>
                  <Node label="Tier 1" xpath="ChannelUnits" type="polygon" symbology="cu_T1" />
                  <Node label="Tier 2" xpath="ChannelUnits" type="polygon" symbology="cu_T2" />
                </Children>
              </Node>
              <Node label="Grain Size Occular Estimates">
                <Children>
                  <Node label="D16" xpath="ChannelUnits" type="polygon" symbology="cu_D16" />
                  <Node label="D50" xpath="ChannelUnits" type="polygon" symbology="cu_D50" />
                  <Node label="D84" xpath="ChannelUnits" type="polygon" symbology="cu_D84" />
                  <Node label="D90" xpath="ChannelUnits" type="polygon" symbology="cu_D90" />
                </Children>
              </Node>
            </Children>
          </Node>

          <Node label="Topographic Survey Data" xpath="Realizations/SurveyData">
            <Children collapsed="true">
              <Node xpathlabel="Name" xpath="SurveyExtents/Vector[@id='survey_extent']" type="polygon" symbology="SurveyExtent" />
              <Node xpathlabel="Name" xpath="Vector[@id='breaklines']" type="line" symbology="breaklines" />
              <Node xpathlabel="Name" xpath="Vector[@id='topo_points']" type="point" symbology="pts_topo" />
              <Node xpathlabel="Name" xpath="Vector[@id='eow_points']" type="point" symbology="pts_eow" />
              <Node xpathlabel="Name" xpath="Vector[@id='control_points']" type="point" symbology="pts_control" />
              <Node xpathlabel="Name" xpath="Vector[@id='stream_features']" type="point" symbology="pts_streamFeatures" />
              <Node xpathlabel="Name" xpath="Vector[@id='error_points']" type="point" symbology="pts_error" />
            </Children>
          </Node>

          <Node label="Topographic Derivatives" xpath="Realizations/Topography/TIN">
            <Children collapsed="true">
              <Node label="DEM Error Model">
                <Children>
                  <Node label="Associated Surfaces">
                    <Children>
                      <Node label="Point Density" xpath="AssocSurfaces/PointDensity" type="raster" symbology="asPD" transparency="40" />
                      <Node label="Slope Analyis" xpath="AssocSurfaces/Slope" type="raster" symbology="asSD" transparency="40" />
                      <Node label="Interpolation Error" xpath="AssocSurfaces/InterpolationError" type="raster" symbology="ErrorDEM" transparency="40" />
                      <Node label="Roughness Height" xpath="AssocSurfaces/Roughness" type="raster" symbology="" transparency="40" />
                    </Children>
                  </Node>
                  <Node label="Error Model(s)">
                    <Children>
                      <Node label="FIS Error Model" xpath="AssocSurfaces/ErrSurface" type="raster" symbology="ErrorDEM" transparency="40" />
                    </Children>
                  </Node>
                </Children>
              </Node>
              <Node label="Hydraulics">
                <Children>
                  <Node xpathlabel="Name" xpath="WaterDepth" type="raster" symbology="wDepth" transparency="40" />
                  <Node xpathlabel="Name" xpath="WaterSurfaceDEM" type="raster" symbology="wsDEM" transparency="40" />
                  <Node xpathlabel="Name" xpath="Thalweg" type="line" symbology="thalweg" />
                </Children>
              </Node>

              <Node label="Mapping">
                <Children collapsed="true">
                  <Node label="Cross Sections, Profiles and Extents">
                    <Children>
                      <Node label="Surveyed Wetted Extent">
                        <Children>
                          <Node label="Wetted Centerline" xpath="Stages/Vector[@id='wetted_centerline']" type="line" symbology="wetCL" />
                          <Node label="Wetted Islands" xpath="Stages/Vector[@id='wetted_islands']" type="polygon" symbology="wetIslands" />
                          <Node label="Wetted Polygon" xpath="Stages/Vector[@id='wetted_extent']" type="polygon" symbology="wetExtent" />
                          <Node label="X-Sections" xpath="Stages/Vector[@id='wetted_crosssections']" type="line" symbology="XS_type" />
                          <Node label="XS QA-QC" xpath="Stages/Vector[@id='wetted_crosssections']" type="line" symbology="XS_qaqc" />
                        </Children>
                      </Node>
                      <Node label="Bankfull Extent">
                        <Children>
                          <Node label="Bankfull Centerline" xpath="Stages/Vector[@id='bankfull_centerline']" type="line" symbology="bfCL" />
                          <Node label="Bankfull Islands" xpath="Stages/Vector[@id='bankfull_islands']" type="polygon" symbology="bfIslands" />
                          <Node label="Bankfull Extent Polygon" xpath="Stages/Vector[@id='bankfull_extent']" type="polygon" symbology="bfExtent" />
                          <Node label="BF X-Sections" xpath="Stages/Vector[@id='bankfull_crosssections']" type="line" symbology="XS_type" />
                          <Node label="BF XS QA-QC" xpath="Stages/Vector[@id='bankfull_crosssections']" type="line" symbology="XS_qaqc" />
                        </Children>
                      </Node>
                    </Children>
                  </Node>

                </Children>
              </Node>
            </Children>
          </Node>

          <Node label="Topography" xpath="Realizations/Topography">
            <Children collapsed="false">
              <Node label="TINs">
                <Children>
                  <Node xpathlabel="Name" xpath="TIN" type="tin" symbology="" />
                  <Node xpathlabel="Name" xpath="TIN/WaterSurfaceTIN" type="tin" symbology="" />
                </Children>
              </Node>
              <Node label="Digital Elevation Models">
                <Children>
                  <Node xpathlabel="Name" xpath="TIN/Detrended" type="raster" symbology="detrendDEM" transparency="40" />
                  <Node xpathlabel="Name" xpath="TIN/DEM" type="raster" symbology="DEM" transparency="40" />
                  <Node xpathlabel="Name" xpath="TIN/DEMHillshade" type="raster" symbology="hillshade" />

                </Children>
              </Node>
            </Children>
          </Node>
        </Children>
      </Node>
      <Node label="Inputs">
        <Children collapsed="true">
          <Node label="Raw Survey Data">
            <Children>
              <Node label="Breaklines CAD DXF file" xpath="Inputs/Vector[@id='BreaklineDXF']" type="file" />
              <Node label="Survey Instrument File (*.mjf)" xpath="Inputs/InstrumentFile" type="file" />
              <Node label="Auxilary RAW Instrument File" xpath="Inputs/AuxInstrumentFile" type="file" />
            </Children>
          </Node>
          <Node label="Survey Quality QA/QC">
            <Children>
              <Node label="Survey Quality SQLite Database" xpath="Inputs/SurveyQualityDB" type="file" />

            </Children>
          </Node>
        </Children>
      </Node>
    </Children>
  </Node>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinesslogic/rvd.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>RVD</Name>
  <ProjectType>RVD</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node xpathlabel="Name" xpath="Realizations/RVD/Outputs/HTMLFile" type="file" />
      <Node label="Inputs" xpath="Realizations/RVD/Inputs">
        <Children>
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='FLOWLINES']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='FLOW_AREA']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='WATERBODIES']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='VALLEY_BOTTOM']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Raster[@id='EXVEG']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Raster[@id='HISTVEG']" type="raster" symbology="" />
        </Children>
      </Node>
      <Node label="Intermediates" xpath="Realizations/RVD/Intermediates">
        <Children collapsed="true">
          <Node label="Thiessen Polygons">
            <Children collapsed="true">
              <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='THIESSEN']" type="vector" symbology="" />
              <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='THIESSEN_POINTS']" type="vector" symbology="" />
              <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='THIESSEN_DISSOLVED']" type="vector" symbology="" />
              <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='THIESSEN_RAW']" type="vector" symbology="" />
            </Children>
          </Node>
          <Node label="Existing Vegetation">
            <Children collapsed="true">
              <Node xpathlabel="Name" xpath="Raster[@id='EXISTING_RAW']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='EXISTING_RIPARIAN']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='EXISTING_NATIVE_RIPARIAN']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='EXISTING_VEGETATED']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='EXISTING_CONVERSION']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='EXISTING_LUI']" type="raster" symbology="" />

            </Children>
          </Node>
          <Node label="Historic Vegetation">
            <Children collapsed="true">
              <Node xpathlabel="Name" xpath="Raster[@id='HISTORIC_RAW']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='HISTORIC_RIPARIAN']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='HISTORIC_NATIVE_RIPARIAN']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='HISTORIC_VEGETATED']" type="raster" symbology="" />
              <Node xpathlabel="Name" xpath="Raster[@id='HISTORIC_CONVERSION']" type="raster" symbology="" />
            </Children>
          </Node>

          <Node xpathlabel="Name" xpath="Raster[@id='RIPARIAN_ZONES']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Raster[@id='NATIVE_RIPARIAN_ZONES']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Raster[@id='VEGETATION_ZONES']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Raster[@id='VEGETATION_CONVERSION']" type="raster" symbology="" />
        </Children>
      </Node>
      <Node label="Outputs" xpath="Realizations/RVD/Outputs">
        <Children>
          <Node label="Riparian Departure" xpath="Geopackage/Layers/Vector[@id='SEGMENTED']" type="vector" id="rvd_output" symbology="RiparianVegetationDeparture" />
          <Node label="Conversion Type" xpath="Geopackage/Layers/Vector[@id='SEGMENTED']" type="vector" id="conversion_type" symbology="RiparianConversionType" />
        </Children>
      </Node>
    </Children>
  </Node>
  <Views default="RVD Output">
    <View name="RVD Output">
      <Layer id="rvd_output" />
      <Layer id="conversion_type" />
    </View>
  </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/Solar.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd"> -->
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XSD/project_explorer.xsd">
    <Name>Solar Insolation</Name>
    <ProjectType>Solar</ProjectType>
    <Node xpathlabel="Name">
        <Children>
            <Repeater label="Realizations" xpath="Realizations/Solar">
                <!-- this is a template for how each realization should render-->
                <Node xpathlabel="Name">
                    <Children collapsed="false">
                        <Node label="Inputs" xpath="Inputs">
                            <Children>
                                <Repeater label="Rasters" xpath="Raster">
                                    <Node xpathlabel="Name" xpath="Raster" type="raster" symbology="" />
                                </Repeater>
                                <Repeater label="Vectors" xpath="Vector">
                                    <Node xpathlabel="Name" xpath="Vector" type="line" symbology="" />
                                </Repeater>
                            </Children>
                        </Node>
                        <Node label="Analyses" xpath="Analyses">
                            <Children>
                                <Node label="Outputs" xpath="Analysis/Outputs">
                                    <Children>
                                        <Node xpathlabel="Name" xpath="Raster" type="raster" symbology="Solar_Raster" />
                                        <Node xpathlabel="Name" xpath="Vector" type="line" symbology="Solar_Vector" />
                                    </Children>
                                </Node>
                            </Children>
                        </Node>
                    </Children>
                </Node>
            </Repeater>
        </Children>
    </Node>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/cad_export.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>CAD Export</Name>
  <ProjectType>cad_export</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization">
    <Children collapsed="false">
      <Node label="Outputs" xpath="Outputs">
        <Children collapsed="false">
          <Node label="Control CSV" xpath="CSV[@id='control_csv']" type="file" />
          <Node label="Topo DXF" xpath="Vector[@id='topo_dxf']" type="file" />
          <Node label="Topo CSV" xpath="CSV[@id='topo_csv']" type="file" />
          <Node label="TIN DXF" xpath="Vector[@id='tin_dxf']" type="file" />
        </Children>
      </Node>
    </Children>
  </Node>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/CHaMPMacroinvertebrate.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>CHaMP Macroinvertebrate</Name>
  <ProjectType>CHaMPMacroinvertebrate</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization[@id='REALIZATION1']">
    <Children collapsed="false">
      <Node label="Macroinvertebrate Habitat Data Static" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='HabitatDataStatic']" type="point" id="macro_habitat_static" />
      <Node label="Drift Data CSV" xpath="Datasets/File[@id='drift_data_csv']" type="file" id="drift_data_csv" />
      <Node label="Dynamic Habitat Data CSV" xpath="Datasets/File[@id='dynamic_habitat_csv']" type="file" id="dynamic_habitat_csv" />
      <Node label="Static Habitat Data CSV" xpath="Datasets/File[@id='static_habitat_csv']" type="file" id="static_habitat_csv" />
    </Children>
  </Node>
  <Views default="DEFAULT">
    <View name="Static Habitat Data" id="DEFAULT">
      <Layers>
        <Layer id="macro_habitat_static" />
      </Layers>
    </View>
  </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/HAND.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd">
    <!-- <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XSD/project_explorer.xsd"> -->
    <Name>VBET</Name>
    <ProjectType>VBET</ProjectType>
    <Node xpathlabel="Name" xpath="Realizations/HAND">
        <Children collapsed="false">
            <Node label="Outputs">
                <Children collapsed="true">
                    <Node label="HAND Raster" xpath="Intermediates/Raster[@id='HAND_RASTER']" type="raster" symbology="hand" transparency="40" />
                </Children>
            </Node>
            <Node label="Inputs">
                <Children collapsed="true">
                    <Node label="Hydrography">
                        <Children collapsed="true">
                            <Node xpathlabel="Name" xpath="Intermediates/Geopackage/Layers/Vector[@id='HAND_NETWORK']" type="line" symbology="" />
                            <Node label="Full NHD HR+ Drainage Network" xpath="Inputs/Geopackage/Layers/Vector[@id='FLOWLINES']" type="line" symbology="flow_lines" />
                            <Node label="Perrenial Drainage Network" xpath="Inputs/Geopackage/Layers/Vector[@id='FLOWLINES']" type="line" symbology="nhdperrenial" />
                            <Node label="Intermittent Drainage Network" xpath="Inputs/Geopackage/Layers/Vector[@id='FLOWLINES']" type="line" symbology="nhdintermittent" />
                            <Node label="Ephemeral Drainage Network" xpath="Inputs/Geopackage/Layers/Vector[@id='FLOWLINES']" type="line" symbology="nhdephemeral" />
                            <Node label="Network - Upstream Drainage Network" xpath="Inputs/Geopackage/Layers/Vector[@id='FLOWLINES']" type="polygon" symbology="upstreamdrainagearea" />
                            <Node label="River Polygons (NHD Area)" xpath="Inputs/Geopackage/Layers/Vector[@id='FLOW_AREA']" type="polygon" symbology="nhdarea" />
                        </Children>
                    </Node>
                    <Node label="Topography">
                        <Children collapsed='true'>
                            <Node label="Slope Analysis" xpath="Inputs/Raster[@id='SLOPE_RASTER']" type="raster" symbology="slope" transparency="40" />
                            <Node label="Height Above Nearest Drainage" xpath="Intermediates/Raster[@id='HAND_RASTER']" type="raster" symbology="hand" transparency="40" />
                            <Node xpathlabel="Name" xpath="Inputs/Raster[@id='HILLSHADE']" type="raster" symbology="" id="hillshade" />
                        </Children>
                    </Node>
                </Children>
            </Node>
            <!-- <Node label="Intermediates">
                <Children collapsed="true">


                </Children>
            </Node> -->
        </Children>
    </Node>
    <Views default="DEFAULT">
        <View name="VBET Default View" id="DEFAULT">
            <Layers>
                <Layer id="hillshade" />
                <Layer id="vbet50" />
            </Layers>
        </View>
    </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/nznational.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
    <!-- <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./XSD/project_explorer.xsd"> -->
    <Name>New Zealand National Datasets</Name>
    <ProjectType>NZNational</ProjectType>
    <Node xpathlabel="Name" xpath="Realizations/Realization">
        <Children>
            <Node label="Hydrography">
                <Children collapsed="false">
                    <Node label="Hydro Net Junctions"
                        xpath="Outputs/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='hydro_net_junctions']"
                        type="point" symbology="hydro_net_junctions" id="hydro_net_junctions" />
                    <Node label="River Network"
                        xpath="Outputs/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='riverlines']"
                        type="line" symbology="hydrography" id="riverlines" />
                    <Node label="Lakes"
                        xpath="Outputs/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='nz_lake_polygons_topo_150k']"
                        type="polygon" symbology="lakes" id="lakes" />
                    <Node label="Catchment Wings"
                        xpath="Outputs/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='rec2ws']"
                        type="polygon" symbology="catchment_wings" id="catchment_wings" />
                    <Node label="Watersheds"
                        xpath="Outputs/Geopackage[@id='HYDROGRAPHY']/Layers/Vector[@lyrName='watersheds']"
                        type="polygon" symbology="watersheds" id="wateresheds" />
                </Children>
            </Node>
            <Node label="Transportation">
                <Children collapsed="false">
                    <Node label="Roads"
                        xpath="Outputs/Geopackage[@id='TRANSPORTATION']/Layers/Vector[@lyrName='nzroadcentrelinestopo150k']"
                        type="line" symbology="nz_roads" id="roads" />
                    <Node label="Railways"
                        xpath="Outputs/Geopackage[@id='TRANSPORTATION']/Layers/Vector[@lyrName='nz-railway-centrelines-topo-150k']"
                        type="line" symbology="nz_railways" id="railways" />
                </Children>
            </Node>
            <Node label="Topography">
                <Children collapsed="false">
                    <Node label="DEM North Island"
                        xpath="Outputs/Raster[@id='DEMNORTH']"
                        type="raster" symbology="dem" id="demnorth" />
                    <Node label="DEM South Island"
                        xpath="Outputs/Raster[@id='DEMSOUTH']"
                        type="raster" symbology="dem" id="demsouth" />
                </Children>
            </Node>
            <Node label="Administration">
                <Children collapsed="false">
                    <Node label="New Zealand Regional Councils 2023"
                        xpath="Outputs/Geopackage[@id='ADMINISTRATION']/Layers/Vector[@lyrName='regional_council_2023_generalised']"
                        type="polygon" symbology="regional_councils" id="regional_councils" />
                </Children>
            </Node>
        </Children>
    </Node>
    <Views default="Default">
        <View name="Hydrology" id="Default">
            <Layers>
                <Layer id="riverlines" />
            </Layers>
        </View>
    </Views>
</Project>
