=== Riverscapes/RiverscapesXML/RaveBusinesslogic/XSD/project_explorer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Overall Structure  -->
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Name"/>
        <xs:element type="xs:string" name="Description" minOccurs="0"/>
        <xs:element type="xs:string" name="ProjectType" minOccurs="1" maxOccurs="1"/>
        <xs:element type="NodeType" name="Node"/>
        <xs:element type="ViewsType" name="Views" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Allowable things to add to the map-->
  <xs:simpleType name="datatype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vector" />
      <xs:enumeration value="raster" />
      <xs:enumeration value="tile" />
      <xs:enumeration value="file" />
      <xs:enumeration value="tin" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Node: A one-off tree branch that has an xpath -->
  <xs:complexType name="NodeType">
    <xs:sequence>
      <xs:element type="xs:string" name="Tileservice" minOccurs="0"/>
      <xs:element type="ChildrenType" name="Children" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="optional"/>
    <xs:attribute type="datatype" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="symbology" use="optional"/>
    <xs:attribute type="xs:integer" name="transparency" use="optional" />
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>

  <!-- Repeaters: loop over xml node "arrays" -->
  <xs:complexType name="RepeaterType">
    <xs:sequence>
      <xs:choice>
        <xs:element type="NodeType" name="Node" maxOccurs="1"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="required"/>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!--Children is basically just a bucket that can contain nodes and repeaters-->
  <xs:complexType name="ChildrenType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="NodeType" name="Node" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element type="RepeaterType" name="Repeater" minOccurs="1" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!-- There can be one Views node that contains many views-->
  <xs:complexType name="ViewsType">
    <xs:sequence>
      <xs:element type="ViewType" name="View" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="default" use="optional"/>
  </xs:complexType>

  <!-- Each view is a sequence of layers-->
  <xs:complexType name="ViewType">
    <xs:sequence>
      <xs:element type="LayerType" name="Layer" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>

  <!-- Each layer refers to a node by id and determins if the layer should be turned "on" and visible in the map-->
  <xs:complexType name="LayerType">
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:boolean" name="visible" use="optional"/>
  </xs:complexType>
</xs:schema>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/Topo.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>CHaMP Topo</Name>
  <ProjectType>Topo</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node label="Topo">
        <Children>
          <Node label="Auxiliary Survey Data" xpath="Realizations/Realization[@id='topography']">
            <Children collapsed="true">
              <Node label="Channel Units">
                <Children>
                  <Node label="Unit ID" xpath="Outputs/Vector[@id='ChannelUnits']" type="polygon" symbology="cu_UnitNum" />
                </Children>
              </Node>
              <Node label="Hawkins Channel Units">
                <Children>
                  <Node label="Tier 1" xpath="Outputs/Vector[@id='ChannelUnits']" type="polygon" symbology="cu_T1" />
                  <Node label="Tier 2" xpath="Outputs/Vector[@id='ChannelUnits']" type="polygon" symbology="cu_T2" />
                </Children>
              </Node>
              <Node label="Grain Size Occular Estimates">
                <Children>
                  <Node label="D16" xpath="Outputs/Vector[@id='ChannelUnits']" type="polygon" symbology="cu_D16" />
                  <Node label="D50" xpath="Outputs/Vector[@id='ChannelUnits']" type="polygon" symbology="cu_D50" />
                  <Node label="D84" xpath="Outputs/Vector[@id='ChannelUnits']" type="polygon" symbology="cu_D84" />
                  <Node label="D90" xpath="Outputs/Vector[@id='ChannelUnits']" type="polygon" symbology="cu_D90" />
                </Children>
              </Node>
            </Children>
          </Node>
          <Node label="Topographic Survey Data" xpath="Realizations/Realization[@id='survey_data_projected']">
            <Children collapsed="true">
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='survey_extent']" type="polygon" symbology="SurveyExtent" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='breaklines']" type="line" symbology="breaklines" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='topo_points']" type="point" symbology="pts_topo" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='eow_points']" type="point" symbology="pts_eow" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='control_points']" type="point" symbology="pts_control" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='stream_features']" type="point" symbology="pts_streamFeatures" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='error_points']" type="point" symbology="pts_error" />
            </Children>
          </Node>
          <Node label="Topographic Derivatives" xpath="Realizations/Realization[@id='topography']">
            <Children collapsed="true">
              <Node label="DEM Error Model">
                <Children>
                  <Node label="Associated Surfaces">
                    <Children>
                      <Node label="Point Density" xpath="Outputs/Raster[@id='PointDensity']" type="raster" symbology="asPD" transparency="40" />
                      <Node label="Slope Analyis" xpath="Outputs/Raster[@id='Slope']" type="raster" symbology="asSD" transparency="40" />
                      <Node label="Interpolation Error" xpath="Outputs/Raster[@id='InterpolationError']" type="raster" symbology="ErrorDEM" transparency="40" />
                      <Node label="Roughness Height" xpath="Outputs/Raster[@id='Roughness']" type="raster" symbology="" transparency="40" />
                      <Node label="3D Point Quality" xpath="Outputs/Raster[@id='PointQuality3D']" type="raster" symbology="" transparency="40" />
                    </Children>
                  </Node>
                  <Node label="Error Model(s)">
                    <Children>
                      <Node label="FIS Error Model" xpath="Outputs/Raster[@id='ErrSurface']" type="raster" symbology="ErrorDEM" transparency="40" />
                    </Children>
                  </Node>
                </Children>
              </Node>
              <Node label="Hydraulics">
                <Children>
                  <Node xpathlabel="Name" xpath="Outputs/Raster[@id='WaterDepth']" type="raster" symbology="wDepth" transparency="40" id="water_depth"/>
                  <Node xpathlabel="Name" xpath="Outputs/Raster[@id='WaterSurfaceDEM']" type="raster" symbology="wsDEM" transparency="40" />
                  <Node xpathlabel="Name" xpath="Outputs/Vector[@id='thalweg']" type="line" symbology="thalweg" />
                </Children>
              </Node>
              <Node label="Mapping">
                <Children collapsed="true">
                  <Node label="Cross Sections, Profiles and Extents">
                    <Children>
                      <Node label="Surveyed Wetted Extent">
                        <Children>
                          <Node label="Wetted Centerline" xpath="Outputs/Vector[@id='wetted_centerline']" type="line" symbology="wetCL" />
                          <Node label="Wetted Islands" xpath="Outputs/Vector[@id='wetted_islands']" type="polygon" symbology="wetIslands" />
                          <Node label="Wetted Polygon" xpath="Outputs/Vector[@id='wetted_extent']" type="polygon" symbology="wetExtent" />
                          <Node label="X-Sections" xpath="Outputs/Vector[@id='wetted_crosssections']" type="line" symbology="XS_type" />
                          <Node label="XS QA-QC" xpath="Outputs/Vector[@id='wetted_crosssections']" type="line" symbology="XS_qaqc" />
                        </Children>
                      </Node>
                      <Node label="Bankfull Extent">
                        <Children>
                          <Node label="Bankfull Centerline" xpath="Outputs/Vector[@id='bankfull_centerline']" type="line" symbology="bfCL" />
                          <Node label="Bankfull Islands" xpath="Outputs/Vector[@id='bankfull_islands']" type="polygon" symbology="bfIslands" />
                          <Node label="Bankfull Extent Polygon" xpath="Outputs/Vector[@id='bankfull_extent']" type="polygon" symbology="bfExtent" />
                          <Node label="BF X-Sections" xpath="Outputs/Vector[@id='bankfull_crosssections']" type="line" symbology="XS_type" />
                          <Node label="BF XS QA-QC" xpath="Outputs/Vector[@id='bankfull_crosssections']" type="line" symbology="XS_qaqc" />
                        </Children>
                      </Node>
                    </Children>
                  </Node>
                </Children>
              </Node>
            </Children>
          </Node>
          <Node label="Topography" xpath="Realizations/Realization[@id='topography']">
            <Children collapsed="false">
              <!-- <Node label="TINs">
                <Children>
                  <Node xpathlabel="Name" xpath="Inputs/TIN" symbology="" type="tin"/>
                  <Node xpathlabel="Name" xpath="Outputs/TIN[@id='WaterSurfaceTIN'" type="tin" symbology="" />
                </Children>
              </Node> -->
              <Node label="Digital Elevation Models">
                <Children>
                  <Node xpathlabel="Name" xpath="Outputs/Raster[@id='Detrended']" type="raster" symbology="detrendDEM" transparency="40" />
                  <Node xpathlabel="Name" xpath="Outputs/Raster[@id='DEM']" type="raster" symbology="dem" transparency="40" id="dem"/>
                  <Node xpathlabel="Name" xpath="Outputs/HillShade[@id='DEMHillshade']" type="raster" symbology="hillshade" id="dem_hillshade"/>
                </Children>
              </Node>
            </Children>
          </Node>
        </Children>
      </Node>
      <Node label="Inputs">
        <Children collapsed="true">
          <Node label="Raw Survey Data">
            <Children>
              <Node label="Breaklines CAD DXF file" xpath="CommonDatasets/Vector[@id='BreaklineDXF']" type="file" />
              <Node label="Survey Instrument File (*.mjf)" xpath="CommonDatasets/InstrumentFile" type="file" />
              <Node label="Auxilary RAW Instrument File" xpath="CommonDatasets/AuxInstrumentFile" type="file" />
              <Node label="Channel Units CSV" xpath="CommonDatasets/CSV[@id='channelunitcsv']" type="file" />
            </Children>
          </Node>
          <Node label="Survey Quality QA/QC">
            <Children>
              <Node label="Survey Quality SQLite Database" xpath="CommonDatasets/SurveyQualityDB" type="file" />
            </Children>
          </Node>
        </Children>
      </Node>
    </Children>
  </Node>
      <Views default="DEFAULT">
      <View name="Topography with Water Depth" id="DEFAULT">
        <Layers>
          <Layer id="water_depth" />
          <Layer id="dem" />
          <Layer id="dem_hillshade" />
        </Layers>
      </View>
    </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/hydro_context.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>Hydrologic Context</Name>
  <ProjectType>hydro_context</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization">
    <Children collapsed="false">
      <Node label="Project Report" xpath="Outputs/HTMLFile" type="report" />
      <Node label="Outputs" xpath="Outputs">
        <Children collapsed="false">
          <Node label="Channel Network">
            <Children>
              <Node label="Baseflow (cfs)" xpath="Geopackage/Layers/Vector[@lyrName='vwReaches']" type="line" id="baseflow" symbology="reach_baseflow" />
              <Node label="Typical Flood (cfs)" xpath="Geopackage/Layers/Vector[@lyrName='vwReaches']" type="line" id="flood" symbology="reach_flood" />
              <Node label="Baseflow Stream Power (watts)" xpath="Geopackage/Layers/Vector[@lyrName='vwReaches']" type="line" id="reach_baseflow_sp" symbology="reach_low_stream_power" />
              <Node label="Flood Stream Power (watts)" xpath="Geopackage/Layers/Vector[@lyrName='vwReaches']" type="line" id="reach_flood_sp" symbology="reach_q2_stream_power" />  
            </Children>
          </Node>
          <Node label="Riverscape Network">
            <Children>
              <Node label="Baseflow (IGO) (cfs)" xpath="Geopackage/Layers/Vector[@lyrName='vwIgos']" type="point" id="igo_baseflow" symbology="igo_baseflow" />
              <Node label="Flood (IGO) (cfs)" xpath="Geopackage/Layers/Vector[@lyrName='vwIgos']" type="point" id="igo_flood" symbology="igo_flood" />
              <Node label="Baseflow Stream Power (IGO) (watts)" xpath="Geopackage/Layers/Vector[@lyrName='vwIgos']" type="point" id="igo_baseflow_sp" symbology="igo_low_stream_power" />
              <Node label="Flood Stream Power (IGO) (watts)" xpath="Geopackage/Layers/Vector[@lyrName='vwIgos']" type="point" id="igo_flood_sp" symbology="igo_q2_stream_power" />
            </Children>
          </Node>
        </Children>
      </Node>
      <Node label="Intermediates">
        <Children collapsed="true">
          <Node label="Slope" xpath="Outputs/Geopackage/Layers/Vector[@lyrName='vwReaches']" type="line" symbology="slope" id="slope" />
          <Node label="Drainage Area" xpath="Outputs/Geopackage/Layers/Vector[@lyrName='vwReaches']" type="line" symbology="drain_area" id="DA" />
        </Children>
      </Node>
      <Node label="Inputs" xpath="Inputs">
        <Children collapsed="true">
          <Node label="Segmented Flowlines" xpath="Geopackage/Layers/Vector[@lyrName='flowlines']" type="line" symbology="flowlines" />
          <Node label="Integrated Geographic Objects" xpath="Geopackage/Layers/Vector[@lyrName='igo']" type="point" symbology="IGO" />
          <Node label="Discrete Geographic Objects" xpath="Geopackage/Layers/Vector[@lyrName='dgo']" type="point" symbology="DGO" />
          <Node label="Digital Elevation Model" xpath="Raster[@id='DEM']" type="raster" id="dem" symbology="dem" transparency="40" />
        </Children>
      </Node>
      <Node label="Hillshade" xpath="Inputs">
        <Children>
          <Node label="Hillshade" xpath="Raster[@id='HILLSHADE']" type="raster" id="hillshade" symbology="hillshade" />
        </Children>
      </Node>
    </Children>
  </Node>
  <Views default="Q2">
    <View name="Typical Flood" id="Q2">
      <Description>Predicted values for a typical two-year flood attributed to the channel network</Description>
      <Layers>
        <Layer id="flood" />
        <Layer id="hillshade" />
      </Layers>
    </View>
  </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/LTPBRProjects.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>LTPBR Projects</Name>
  <ProjectType>ltpbrprojects</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization">
    <Children collapsed="false">
      <Node label="Outputs" xpath="Datasets">
        <Children collapsed="false">
          <Node label="LTPBR Projects" xpath="Geopackage/Layers/Vector[@lyrName='projects']" type="point" id="projects" symbology="ltpbr_projects" />
          <Node label="Outputs Geopackage (SQLite Database)" xpath="Geopackage" type="file" /> 
        </Children>
      </Node>
      </Children>
  </Node>
  <Views default="DEFAULT">
    <View name="LTPBR Projects" id="DEFAULT">
      <Layers>
        <Layer id="projects" />
      </Layers>
    </View>
  </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/Substrate.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>Substrate</Name>
  <ProjectType>Substrate</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/Realization">
    <Children collapsed="false">
      <Node label="Outputs">
        <Children collapsed="false">
          <Node label="Substrate Shapefile" xpath="Outputs/Vector[Name='Substrate_Shapefile']" type="polygon" />
          <Node label="Substrate Raster" xpath="Outputs/Vector[Name='Substrate_Raster']" type="raster" transparency="50" />
        </Children>
      </Node>
    </Children>
  </Node>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/confinement.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>Confinement</Name>
  <ProjectType>CONFINEMENT</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node xpathlabel="Name" xpath="Realizations/Confinement/Outputs/HTMLFile" type="file" />
      <Node label="Outputs">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Outputs/Geopackage/Layers/Vector[@id='CONFINEMENT_RAW']" type="vector" id="confinement_raw" symbology="confinement_raw" />
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Outputs/Geopackage/Layers/Vector[@id='CONFINEMENT_MARGINS']" type="vector" id="confinement_margins" symbology="confinement_margins" />
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Outputs/Geopackage/Layers/Vector[@id='CONFINEMENT_RATIO']" type="vector" id="confinement_ratio" symbology="confinement_ratio" />
          <Node label="Constriction Ratio" xpath="Realizations/Confinement/Outputs/Geopackage/Layers/Vector[@id='CONFINEMENT_RATIO']" type="vector" id="constriction_ratio" symbology="constriction_ratio" />
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Outputs/Geopackage/Layers/Vector[@id='CONFINEMENT_BUFFERS']" type="vector" id="confinement_buffer" symbology="" />
        </Children>
      </Node>
      <Node label="Inputs">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Inputs/Geopackage/Layers/Vector[@id='FLOWLINES']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Inputs/Geopackage/Layers/Vector[@id='CONFINING_POLYGON']" type="vector" id="confining_poly" symbology="" />
        </Children>
      </Node>
      <Node label="Intermediates">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Intermediates/Geopackage/Layers/Vector[@id='SPLIT_POINTS']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Intermediates/Geopackage/Layers/Vector[@id='FLOWLINE_SEGMENTS']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Intermediates/Geopackage/Layers/Vector[@id='ERROR_POLYLINES']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/Confinement/Intermediates/Geopackage/Layers/Vector[@id='ERROR_POLYGONS']" type="vector" symbology="" />
        </Children>
      </Node>
    </Children>
  </Node>
  <Views default="CONFINEMENT_RATIO"> 
    <View name="Confinement Ratio by Stream Segment" id="CONFINEMENT_RATIO"> 
      <Layer id="confining_poly" />
      <Layer id="confinement_ratio" />
    </View>
    <View name="Constriction Ratio by Stream Segment" id="CONSTRICTION_RATIO"> 
      <Layer id="confining_poly" />
      <Layer id="constriction_ratio" />
    </View>
    <View name="Confinement Type by Stream Segment" id="CONFINEMENT_TYPE"> 
      <Layer id="confining_poly" />
      <Layer id="confinement_raw" /> 
    </View>
  </Views> 
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/V2/RSDynamics.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://xml.riverscapes.net/RaveBusinessLogic/XSD/project_explorer.xsd">
  <Name>Riverscapes Dynamics</Name>
  <ProjectType>RSDynamics</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node label="Outputs" xpath="Realizations/Realization/Datasets">
        <Children collapsed="true">
          <Node label="VBET IGOs"
            xpath="Geopackage/Layers/Vector[@lyrName='vw_igo_metrics']"
            type="point" id="vbet_igos_stdev" symbology="igo_zstat_stdev" />
          <Node label="VBET DGOs"
            xpath="Geopackage/Layers/Vector[@lyrName='vbet_dgos']"
            type="polygon" symbology="vbet_dgos" id="vbet_dgos_raw" />
          <Node label="30yr Dynamics Alluvial Raster"
            xpath="Raster[@id='ALLUVIAL_30YR']"
            type="raster" symbology="dynamics_raster" id="alluvial_30yr" />
        </Children>
      </Node>
      <Node xpathlabel="Name" xpath="CommonDatasets/Raster[@id='HILLSHADE']" type="raster"
        transparency="40" symbology="hillshade" id="hillshade" />
    </Children>
  </Node>
  <Views default="DEFAULT">
    <View name="Primary Outputs" id="DEFAULT">
      <Layers>
        <Layer id="vbet_igos_stdev" />
        <Layer id="vbet_dgos_raw" />
        <Layer id="alluvial_30yr" />
        <Layer id="hillshade" />
      </Layers>
    </View>
  </Views>
</Project>

=== Riverscapes/RiverscapesXML/RaveBusinessLogic/default.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/RaveBusinessLogic/XSD/project_explorer.xsd"> -->
  <Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XSD/project_explorer.xsd">
    <Name>Default</Name>
    <ProjectType>Default</ProjectType>
    <Node xpathlabel="Name">
      <Children>
        <Repeater label="Realizations" xpath="Realizations/*">
          <!--This is a template for how each realization should render-->
          <Node xpathlabel="Name">
            <Children collapsed="false">
              <Node label="Inputs" xpath="Inputs">
                <Children>
                  <Repeater label="Raster Layers" xpath="//Raster">
                    <Node xpathlabel="Name" type="raster" symbology="" />
                  </Repeater>
                  <Repeater label="Vector Layers" xpath="//Vector">
                    <!-- TODO: this is a problem we need to address -->
                    <Node xpathlabel="Name" type="polygon" symbology="" />
                  </Repeater>
                  <Repeater label="Image Layers" xpath="//Image">
                    <Node xpathlabel="Name" type="file" />
                  </Repeater>
                </Children>
              </Node>
            </Children>
          </Node>
        </Repeater>
      </Children>
    </Node>
  </Project>
