=== Riverscapes/RiverscapesXML/Projects/XSD/V1/RiverscapesProject.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsL="http://www.w3.org/2001/XMLSchema">

  <!-- =========================================================================
  
  Common Elements:
  - All projects must have the Following:
  
  ============================================================================== -->
  <!-- Top Leve item: Here's where the overall project gets Defined -->
  <xs:complexType name="ProjectBaseType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="Name" minOccurs="1" maxOccurs="1" />
      <xs:element type="xs:string" name="ProjectType" minOccurs="1" maxOccurs="1" />
      <xs:element type="MetaDataType" name="Warehouse" minOccurs="0" maxOccurs="1" />
      <xs:element type="MetaDataType" name="MetaData" minOccurs="1" maxOccurs="1" />
      <xs:element type="DataSetContainerType" name="Inputs" minOccurs="0" maxOccurs="1" />
      <!-- <xs:element type="RealizationsBaseType" name="Realizations" minOccurs="1" maxOccurs="1" /> -->
    </xs:sequence>
  </xs:complexType>

  <!-- <xs:complexType name="RealizationsBaseType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="RealizationType" name="Realization" maxOccurs="unbounded" minOccurs="0" />
    </xs:choice>
  </xs:complexType> -->


  <!-- A Project can have realizations -->
  <xs:complexType name="RealizationType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="Name" minOccurs="1" maxOccurs="1" />
      <xs:element type="MetaDataType" name="MetaData" minOccurs="0" maxOccurs="1" />
      <xs:element type="ParametersType" name="Parameters" minOccurs="0" maxOccurs="1" />
      <xs:element type="SimpleFileType" name="LogFile" minOccurs="0" maxOccurs="1" />
      <!-- <xs:element type="DataSetContainerType" name="Inputs" minOccurs="0" maxOccurs="1" />
      <xs:element type="DataSetContainerType" name="Intermediates" minOccurs="0" maxOccurs="1" />
      <xs:element type="DataSetContainerType" name="Outputs" minOccurs="0" maxOccurs="1" /> -->
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required" />
    <xs:attribute type="xs:boolean" name="promoted" use="optional" />
    <xs:attribute type="xs:string" name="dateCreated" use="required" />
    <xs:attribute type="xs:string" name="productVersion" use="required" />
    <xs:attribute type="xs:string" name="guid" />
  </xs:complexType>

  <!--Realizations Must have an Analyses-->
  <xs:complexType name="AnalysesType" mixed="true">
    <xs:sequence>
      <xs:element type="AnalysisType" name="Analysis" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>


  <!--Realizations Must have an Analysis-->
  <xs:complexType name="AnalysisType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="Name" minOccurs="0" />
      <xs:element type="MetricsType" name="Metrics" minOccurs="0" />
      <xs:element type="DataSetContainerType" name="Outputs" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <!-- The type of string in the <Meta> tag. These are optional -->
  <xs:simpleType name="KeyValueType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="guid" />
      <xs:enumeration value="url" />
      <xs:enumeration value="path" />
      <xs:enumeration value="imgurl" />
      <xs:enumeration value="isodate" />
      <xs:enumeration value="timestamp" />
      <xs:enumeration value="float" />
      <xs:enumeration value="int" />
      <xs:enumeration value="richtext" />
      <xs:enumeration value="markdown" />
      <xs:enumeration value="json" />
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="MetaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required" />
        <xs:attribute type="KeyValueType" name="type" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MetaDataType">
    <xs:sequence>
      <xs:element type="MetaType" name="Meta" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required" />
        <xs:attribute type="KeyValueType" name="type" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ParametersType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="MetricType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MetricsType">
    <xs:sequence>
      <xs:element type="MetricType" name="Metric" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <!-- =========================================================================
  
  Datasets: Inputs, Outputs, files etc....
  
  ============================================================================== -->

  <!-- Let's define our Input/Output Containers and what they can contain -->
  <xs:complexType name="DataSetContainerType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <!-- A scalar value is possible as an input or an output but use <Params> if you can -->
      <xs:element type="xs:string" name="Value" />
      <xs:element type="RasterType" name="Raster" />
      <xs:element type="RasterType" name="Cover" />
      <xs:element type="RasterType" name="Substrate" />
      <xs:element type="RasterType" name="Velocity" />
      <xs:element type="RasterType" name="Depth" />
      <xs:element type="VectorType" name="Vector" />
      <xs:element type="GeopackageType" name="Geopackage" />
      <xs:element type="VectorType" name="StreamNetwork" />
      <xs:element type="TINType" name="TIN" />
      <xs:element type="DEMType" name="DEM" />
      <xs:element type="HillShadeType" name="HillShade" />
      <xs:element type="SimpleFileType" name="CSV" />
      <xs:element type="SimpleFileType" name="Image" />
      <xs:element type="SimpleFileType" name="Video" />
      <xs:element type="SimpleFileType" name="DataTable" />
      <xs:element type="SimpleFileType" name="Database" />
      <xs:element type="SimpleFileType" name="SurveyQualityDB" />
      <xs:element type="SimpleFileType" name="InstrumentFile" />
      <xs:element type="SimpleFileType" name="AuxInstrumentFile" />
      <xs:element type="SimpleFileType" name="MSAccessDB" />
      <xs:element type="SimpleFileType" name="SQLiteDB" />
      <xs:element type="SimpleFileType" name="PDF" />
      <xs:element type="SimpleFileType" name="HTMLFile" />
      <xs:element type="SimpleFileType" name="ZipFile" />
    </xs:choice>
  </xs:complexType>

  <!-- The base type  -->
  <xs:complexType name="DataSetType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="Name" minOccurs="0" maxOccurs="1" />
      <!--Path is ALWAYS relative inside a project-->
      <xs:element type="xs:string" name="Path" minOccurs="0" maxOccurs="1" />
      <xs:element type="xs:string" name="Project" minOccurs="0" maxOccurs="1" />
      <xs:element type="MetaDataType" name="MetaData" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" />
    <xs:attribute type="xs:string" name="guid" />
    <xs:attribute type="xs:string" name="ref" />
  </xs:complexType>

  <!-- Now some Subtypes -->
  <xs:complexType name="GeoSpatialType">
    <xs:complexContent>
      <xs:extension base="DataSetType" />
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ContextLayerType" mixed="true">
    <xs:complexContent>
      <xs:extension base="DataSetType">
        <xs:sequence>
          <xs:element type="xs:string" name="URL" default="http://" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="SimpleFileType">
    <xs:complexContent>
      <xs:extension base="DataSetType" />
    </xs:complexContent>
  </xs:complexType>

  <!-- Here are the GeoSpatial Types-->
  <xs:complexType name="RasterType">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType" />
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TINType">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType" />
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="VectorType">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType" />
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="GeopackageType" mixed="true">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType">
        <xs:sequence>
          <xs:element type="GeopackageLayersType" name="Layers" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="GeopackageLayersType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="RasterType" name="Raster" />
      <xs:element type="VectorType" name="Vector" />
    </xs:choice>
  </xs:complexType>


  <!-- DEMs extend rasters -->
  <xs:complexType name="DEMType">
    <xs:complexContent>
      <xs:extension base="RasterType" />
    </xs:complexContent>
  </xs:complexType>

  <!-- Here are our context layers -->
  <xs:complexType name="HillShadeType">
    <xs:complexContent>
      <xs:extension base="ContextLayerType" />
    </xs:complexContent>
  </xs:complexType>


  <!-- =========================================================================
  
  Realizations: This is where things get custom for each type of thing.
  
  ============================================================================== -->

</xs:schema>

=== Riverscapes/RiverscapesXML/Projects/XSD/V2/examples/BRAT.xml
<?xml version="1.0" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../RiverscapesProject.xsd">
	<Name>BRAT for HUC 16050304</Name>
	<ProjectType>BRAT</ProjectType>
	<!-- apiUrl is taken from examples/VBET.xml May not be correct-->
	<Warehouse id="63bfb8e2-b9c3-49e1-861e-1e97d7455a5a" apiUrl="https://12312312.amazon.ca/api/prod"></Warehouse>
	<MetaData>
		<Meta name="ModelVersion">4.3.0</Meta>
		<Meta name="dateCreated" type="isodate">2021-09-13T18:05:52.241097</Meta>
		<Meta name="HUC8">16050304</Meta>
		<Meta name="HUC">16050304</Meta>
		<Meta name="BRATBuildVersion">4.3.0</Meta>
		<Meta name="BRATBuildTimestamp">1631556352</Meta>
		<Meta name="Runner">Cybercastor</Meta>
		<Meta name="BRAT_Build_DateTime">2021-09-13T18:06:03.266026</Meta>
		<Meta name="Streamside_Buffer">30.0</Meta>
		<Meta name="Riparian_Buffer">100.0</Meta>
		<Meta name="Reach_Codes">33400,33600,33601,33603,46000,46003,46006,46007,55800</Meta>
		<Meta name="Canal_Codes">33600,33601,33603</Meta>
		<Meta name="Max_Waterbody">0.001</Meta>
		<Meta name="Elevation_Buffer">100.0</Meta>
		<Meta name="gdal_srs_proj4">+proj=longlat +datum=WGS84 +no_defs</Meta>
		<Meta name="gdal_srs_axis_mapping_strategy">0</Meta>
		<Meta name="Watershed">Walker Lake</Meta>
		<Meta name="BratBuildProcTimeS" type="int">943.98</Meta>
		<Meta name="BratBuildProcTimeHuman">15:43 minutes</Meta>
		<Meta name="BRATRunVersion">4.3.0</Meta>
		<Meta name="BRATRunTimestamp" type="timestamp">1631557304</Meta>
		<Meta name="BratRunProcTimeS" type="int">196.96</Meta>
		<Meta name="BratRunProcTimeHuman">3:16 minutes</Meta>
	</MetaData>
	<ProjectBounds>
		<Centroid>
			<Lat>38.528908069922934</Lat>
			<Lng>-118.60960419803286</Lng>
		</Centroid>
		<BoundingBox>
			<MinLat>38.10684594444518</MinLat>
			<MinLng>-118.85150761104612</MinLng>
			<MaxLat>38.849453807743636</MaxLat>
			<MaxLng>-118.30313087628299</MaxLng>
		</BoundingBox>
		<Path>project_bounds.geojson</Path>
	</ProjectBounds>
	<Realizations>
		<Realization id="BRAT" dateCreated="2021-09-13T18:05:52.244153" productVersion="4.3.0">
			<Name>BRAT for HUC 16050304</Name>
      <Logs>
        <LogFile id="LOGFILE">
          <Name>Log</Name>
          <Path>brat_build.log</Path>
        </LogFile>
        <LogFile id="LOGFILE2">
          <Name>Log</Name>
          <Path>brat_build.log</Path>
        </LogFile>
      </Logs>
			<Inputs>
				<DEM id="DEM">
					<Name>NED 10m DEM</Name>
					<Path>inputs/dem.tif</Path>
					<MetaData>
						<Meta name="_rs_wh_id">3d2ab499-568b-4007-b37a-25a241c1622e</Meta>
						<Meta name="_rs_wh_user">21c4df56-9365-4bf2-910a-41c9dedaf35c</Meta>
						<Meta name="_rs_wh_program">Anabranch</Meta>
						<Meta name="_rs_wh_tags">Store</Meta>
						<Meta name="_rs_prj_ModelVersion">1.2.0</Meta>
						<Meta name="_rs_prj_dateCreated" type="isodate">2021-09-10T18:32:36.966632</Meta>
						<Meta name="_rs_prj_HUC8">16050304</Meta>
						<Meta name="_rs_prj_HUC">16050304</Meta>
						<Meta name="_rs_prj_Runner">Cybercastor</Meta>
						<Meta name="_rs_prj_Watershed">Walker Lake</Meta>
						<Meta name="_rs_prj_mean_annual_precipitation_mm" type="float">202.21576663452265</Meta>
						<Meta name="_rs_prj_ProcTimeS" type="int">527.17</Meta>
						<Meta name="_rs_prj_ProcTimeHuman">8:47 minutes</Meta>
						<Meta name="_rs_lyr_Description">National Elevation Dataset (NED) Digital Elevation Models (DEM). These DEMs are downloaded from Science Base and mosaiced into a single 10m DEM that covers the riverscapes context project extent.</Meta>
						<Meta name="_rs_lyr_DocsUrl" type="url">https://tools.riverscapes.net/rscontext/data.html#DEM</Meta>
						<Meta name="_rs_lyr_num_rasters" type="int">1</Meta>
						<Meta name="_rs_lyr_origin_urls" type="json">[&quot;https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/n39w119/USGS_13_n39w119.tif&quot;]</Meta>
						<Meta name="_rs_prj_projType">RSContext</Meta>
						<Meta name="_rs_lyr_id">DEM</Meta>
						<Meta name="_rs_lyr_guid" type="guid">756e8dfc-ee0b-4d92-9a50-aaeab7cac6f2</Meta>
						<Meta name="_rs_lyr_path" type="filepath">topography/dem.tif</Meta>
					</MetaData>
				</DEM>
				<Raster id="EXVEG">
					<Name>Existing Vegetation</Name>
					<Path>inputs/existing_veg.tif</Path>
					<MetaData>
						<Meta name="_rs_wh_id">3d2ab499-568b-4007-b37a-25a241c1622e</Meta>
						<Meta name="_rs_wh_user">21c4df56-9365-4bf2-910a-41c9dedaf35c</Meta>
						<Meta name="_rs_wh_program">Anabranch</Meta>
						<Meta name="_rs_wh_tags">Store</Meta>
						<Meta name="_rs_prj_ModelVersion">1.2.0</Meta>
						<Meta name="_rs_prj_dateCreated" type="isodate">2021-09-10T18:32:36.966632</Meta>
						<Meta name="_rs_prj_HUC8">16050304</Meta>
						<Meta name="_rs_prj_HUC">16050304</Meta>
						<Meta name="_rs_prj_Runner">Cybercastor</Meta>
						<Meta name="_rs_prj_Watershed">Walker Lake</Meta>
						<Meta name="_rs_prj_mean_annual_precipitation_mm" type="float">202.21576663452265</Meta>
						<Meta name="_rs_prj_ProcTimeS" type="int">527.17</Meta>
						<Meta name="_rs_prj_ProcTimeHuman">8:47 minutes</Meta>
						<Meta name="_rs_lyr_Description">LandFire LF REMAP 2019 Existing Vegetation Type (EVT) Raster.The source is a single raster for the entire nation that is downloaded and then clipped to the riverscapes project extent.</Meta>
						<Meta name="_rs_lyr_DocsUrl" type="url">https://tools.riverscapes.net/rscontext/data.html#EXVEG</Meta>
						<Meta name="_rs_prj_projType">RSContext</Meta>
						<Meta name="_rs_lyr_id">EXVEG</Meta>
						<Meta name="_rs_lyr_guid" type="guid">0b75edf1-6921-4af0-9dbd-11279a5673af</Meta>
						<Meta name="_rs_lyr_path" type="filepath">vegetation/existing_veg.tif</Meta>
					</MetaData>
				</Raster>
				<Raster id="HISTVEG">
					<Name>Historic Vegetation</Name>
					<Path>inputs/historic_veg.tif</Path>
					<MetaData>
						<Meta name="_rs_wh_id">3d2ab499-568b-4007-b37a-25a241c1622e</Meta>
						<Meta name="_rs_wh_user">21c4df56-9365-4bf2-910a-41c9dedaf35c</Meta>
						<Meta name="_rs_wh_program">Anabranch</Meta>
						<Meta name="_rs_wh_tags">Store</Meta>
						<Meta name="_rs_prj_ModelVersion">1.2.0</Meta>
						<Meta name="_rs_prj_dateCreated" type="isodate">2021-09-10T18:32:36.966632</Meta>
						<Meta name="_rs_prj_HUC8">16050304</Meta>
						<Meta name="_rs_prj_HUC">16050304</Meta>
						<Meta name="_rs_prj_Runner">Cybercastor</Meta>
						<Meta name="_rs_prj_Watershed">Walker Lake</Meta>
						<Meta name="_rs_prj_mean_annual_precipitation_mm" type="float">202.21576663452265</Meta>
						<Meta name="_rs_prj_ProcTimeS" type="int">527.17</Meta>
						<Meta name="_rs_prj_ProcTimeHuman">8:47 minutes</Meta>
						<Meta name="_rs_lyr_Description">LandFire LF REMAP 2019 Historic Biophysical Settings (BPS) Raster. The source is a single raster for the entire nation that is downloaded and then clipped to the riverscapes project extent.</Meta>
						<Meta name="_rs_lyr_DocsUrl" type="url">https://tools.riverscapes.net/rscontext/data.html#HISTVEG</Meta>
						<Meta name="_rs_prj_projType">RSContext</Meta>
						<Meta name="_rs_lyr_id">HISTVEG</Meta>
						<Meta name="_rs_lyr_guid" type="guid">e9b9c301-69b1-4842-9734-ee33056c9d90</Meta>
						<Meta name="_rs_lyr_path" type="filepath">vegetation/historic_veg.tif</Meta>
					</MetaData>
				</Raster>
				<Raster id="HILLSHADE">
					<Name>DEM Hillshade</Name>
					<Path>inputs/dem_hillshade.tif</Path>
					<MetaData>
						<Meta name="_rs_wh_id">3d2ab499-568b-4007-b37a-25a241c1622e</Meta>
						<Meta name="_rs_wh_user">21c4df56-9365-4bf2-910a-41c9dedaf35c</Meta>
						<Meta name="_rs_wh_program">Anabranch</Meta>
						<Meta name="_rs_wh_tags">Store</Meta>
						<Meta name="_rs_prj_ModelVersion">1.2.0</Meta>
						<Meta name="_rs_prj_dateCreated" type="isodate">2021-09-10T18:32:36.966632</Meta>
						<Meta name="_rs_prj_HUC8">16050304</Meta>
						<Meta name="_rs_prj_HUC">16050304</Meta>
						<Meta name="_rs_prj_Runner">Cybercastor</Meta>
						<Meta name="_rs_prj_Watershed">Walker Lake</Meta>
						<Meta name="_rs_prj_mean_annual_precipitation_mm" type="float">202.21576663452265</Meta>
						<Meta name="_rs_prj_ProcTimeS" type="int">527.17</Meta>
						<Meta name="_rs_prj_ProcTimeHuman">8:47 minutes</Meta>
						<Meta name="_rs_lyr_Description">Hillshade raster generated using the gdal_dem tool specifying the hillshade option.</Meta>
						<Meta name="_rs_lyr_DocsUrl" type="url">https://tools.riverscapes.net/rscontext/data.html#HILLSHADE</Meta>
						<Meta name="_rs_prj_projType">RSContext</Meta>
						<Meta name="_rs_lyr_id">HILLSHADE</Meta>
						<Meta name="_rs_lyr_guid" type="guid">78b4112a-1224-45a4-b8cb-a5cd9bb02939</Meta>
						<Meta name="_rs_lyr_path" type="filepath">topography/dem_hillshade.tif</Meta>
					</MetaData>
				</Raster>
				<Raster id="SLOPE">
					<Name>Slope Raster</Name>
					<Path>inputs/slope.tif</Path>
					<MetaData>
						<Meta name="_rs_wh_id">3d2ab499-568b-4007-b37a-25a241c1622e</Meta>
						<Meta name="_rs_wh_user">21c4df56-9365-4bf2-910a-41c9dedaf35c</Meta>
						<Meta name="_rs_wh_program">Anabranch</Meta>
						<Meta name="_rs_wh_tags">Store</Meta>
						<Meta name="_rs_prj_ModelVersion">1.2.0</Meta>
						<Meta name="_rs_prj_dateCreated" type="isodate">2021-09-10T18:32:36.966632</Meta>
						<Meta name="_rs_prj_HUC8">16050304</Meta>
						<Meta name="_rs_prj_HUC">16050304</Meta>
						<Meta name="_rs_prj_Runner">Cybercastor</Meta>
						<Meta name="_rs_prj_Watershed">Walker Lake</Meta>
						<Meta name="_rs_prj_mean_annual_precipitation_mm" type="float">202.21576663452265</Meta>
						<Meta name="_rs_prj_ProcTimeS" type="int">527.17</Meta>
						<Meta name="_rs_prj_ProcTimeHuman">8:47 minutes</Meta>
						<Meta name="_rs_lyr_Description">Slope raster generated using gdal_dem tool specifying the slope option. Units are in percent.</Meta>
						<Meta name="_rs_lyr_DocsUrl" type="url">https://tools.riverscapes.net/rscontext/data.html#SLOPE</Meta>
						<Meta name="_rs_prj_projType">RSContext</Meta>
