=== Riverscapes/RiverscapesXML/QRiS/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    attributeFormDefault="unqualified" 
    elementFormDefault="qualified" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Top Level Protocol Schema -->
    <xs:element name="Protocol">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Citation" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Author" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="CreationDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="UpdatedDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element type="MetaDataType" name="MetaData" minOccurs="0" maxOccurs="1">
                    <xs:unique name="UniqueMetadataKeys">
                        <xs:selector xpath="./Meta" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
                <xs:element name="Layers" type="LayersType" minOccurs="1" maxOccurs="1">
                    <xs:key name="layerID">
                        <xs:selector xpath="Layer"/>
                        <xs:field xpath="@id"/>
                    </xs:key>
                </xs:element>
                <xs:element name="Metrics" type="MetricsType" minOccurs="0" maxOccurs="1">
                    <xs:unique name="UniqueMetricIDVersion">
                        <xs:selector xpath="Metric"/>
                        <xs:field xpath="@id"/>
                        <xs:field xpath="@version"/>
                        <xs:field xpath="@status"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="machine_code" type="MachineCodeType" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="status" type="ProtocolStatusType" use="required"/>
            <xs:attribute name="protocol_type" type="ProtocolTypeType" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Generic Types -->
    <xs:simpleType name="IdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z][a-zA-Z0-9_]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MachineCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z0-9_]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ValuesType">
        <xs:sequence>
            <xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MetaType">
        <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="name" use="required" />
            <xs:attribute type="MetaKeyValueType" name="type" use="optional" />
            <xs:attribute type="xs:boolean" name="locked" use="optional" />
            <xs:attribute type="MetaKeySrcType" name="ext" use="optional" />
        </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

  <xs:complexType name="MetaDataType">
    <xs:sequence>
      <xs:element type="MetaType" name="Meta" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

    <!-- The type of string in the <Meta> tag. These are optional -->
    <xs:simpleType name="MetaKeyValueType">
        <xs:restriction base="xs:string">
        <xs:enumeration value="guid" />
        <xs:enumeration value="url" />
        <xs:enumeration value="filepath" />
        <xs:enumeration value="image" />
        <xs:enumeration value="video" />
        <xs:enumeration value="isodate" />
        <xs:enumeration value="timestamp" />
        <xs:enumeration value="float" />
        <xs:enumeration value="boolean" />
        <xs:enumeration value="int" />
        <xs:enumeration value="richtext" />
        <xs:enumeration value="markdown" />
        <xs:enumeration value="json" />
        <!-- Hidden just means this is rarely useful to humans so never render it directly 
                (it's not secret or private)
        -->
        <xs:enumeration value="hidden" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MetaKeySrcType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="warehouse" />
            <xs:enumeration value="project" />
            <xs:enumeration value="dataset" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GeomType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Point"/>
            <xs:enumeration value="Linestring"/>
            <xs:enumeration value="Polygon"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ProtocolStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="experimental"/>
            <xs:enumeration value="production"/>
            <xs:enumeration value="deprecated"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ProtocolTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="asbuilt"/>
            <xs:enumeration value="design"/>
            <xs:enumeration value="dce"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Layer Types -->
    <xs:complexType name="LayersType">
        <xs:sequence>
            <xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LayerType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Symbology" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MenuItems" type="MenuItemsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Hierarchy" type="HierarchyItemsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Fields" type="LayerFieldsType" minOccurs="0" maxOccurs="1">
                <xs:unique name="uniqueFieldID">
                    <xs:selector xpath="*"/>
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>
            <xs:element type="MetaDataType" name="MetaData" minOccurs="0" maxOccurs="1">
                <xs:unique name="UniqueLayerMetadataKeys">
                    <xs:selector xpath="./Meta" />
                    <xs:field xpath="@name" />
                </xs:unique>
            </xs:element>
        </xs:all>
        <xs:attribute name="id" type="IdType" use="required"/>
        <xs:attribute name="version" type="xs:string" use="required"/>
        <xs:attribute name="geom_type" type="GeomType" use="required"/>
    </xs:complexType>

    <xs:complexType name="MenuItemsType">
        <xs:sequence>
            <xs:element name="MenuItem" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HierarchyItemsType">
        <xs:sequence>
            <xs:element name="HierarchyItem" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LayerFieldsType">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="IntegerField" type="IntegerFieldType"/>
                <xs:element name="FloatField" type="FloatFieldType"/>
                <xs:element name="TextField" type="TextFieldType"/>
                <xs:element name="ListField" type="ListFieldType"/>
                <xs:element name="AttachmentField" type="AttachmentFieldType"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!-- Field Types -->

    <xs:attributeGroup name="BaseFieldAttributes">
        <xs:attribute name="id" type="IdType" use="required"/>
        <xs:attribute name="version" type="xs:string" use="required"/>
        <xs:attribute name="value_required" type="xs:boolean" default="false" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="IntegerFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MinimumValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaximumValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Slider" type="IntegerSliderType" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <xs:complexType name="FloatFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MinimumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaximumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Precision" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Slider" type="FloatSliderType" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <xs:complexType name="IntegerSliderType">
        <xs:attribute name="min" type="xs:integer" use="required"/>
        <xs:attribute name="max" type="xs:integer" use="required"/>
        <xs:attribute name="step" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:complexType name="FloatSliderType">
        <xs:attribute name="min" type="xs:float" use="required"/>
        <xs:attribute name="max" type="xs:float" use="required"/>
        <xs:attribute name="step" type="xs:float" use="required"/>    
    </xs:complexType>

    <!-- Derived Text Field Type -->
    <xs:complexType name="TextFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaxLength" type="xs:integer" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <!-- Derived Attachment Field Type -->
    <xs:complexType name="AttachmentFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaxAttachments" type="xs:integer" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <!-- Derived List Field Type -->
    <xs:complexType name="ListFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Values" type="ListValuesType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DerivedValues" type="DerivedValuesType" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <!-- extend values type to include custom values attribute-->
    <xs:complexType name="ListValuesType">
        <xs:complexContent>
            <xs:extension base="ValuesType">
                <xs:attribute name="allow_custom_values" type="xs:boolean" default="false" use="optional"/>
                <xs:attribute name="allow_multiple_values" type="xs:boolean" default="false" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DerivedValuesType">
        <xs:sequence>
            <xs:element name="DerivedValue" type="DerivedValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DerivedValueType">
        <xs:sequence>
            <xs:element name="InputValue" type="InputValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="output" type="xs:string" use="required"/>
    </xs:complexType>
            
    <xs:complexType name="InputValueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="field_id_ref" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="VisibilityType">
        <xs:sequence>
            <xs:element name="Values" type="ValuesType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="field_id_ref" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Metric Types -->
    <xs:complexType name="MetricsType">
        <xs:sequence>
            <xs:element name="Metric" type="MetricType" minOccurs="1" maxOccurs="unbounded">
                <xs:unique name="uniqueMetricID">
                    <xs:selector xpath="*"/>
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MetricType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultLevel" type="MetricLevelType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="DefinitionURL" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Hierarchy" type="HierarchyItemsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MinimumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaximumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Precision" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Parameters" type="MetricParametersType" minOccurs="0" maxOccurs="1">
            </xs:element>
        </xs:all>
        <xs:attribute name="id" type="IdType" use="required"/>
        <xs:attribute name="version" type="xs:string" use="required"/>
        <xs:attribute name="calculation_machine_code" type="xs:string" use="required"/>
        <xs:attribute name="status" type="MetricStatusType" default="active"/>
    </xs:complexType>

    <xs:simpleType name="MetricStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deprecated"/>
            <xs:enumeration value="experimental"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MetricLevelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Metric"/>
            <xs:enumeration value="Indicator"/>
            <xs:enumeration value="None"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="MetricParametersType">
        <xs:sequence>
            <xs:element name="InputLayer" type="InputLayerType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="DCELayer" type="DCELayerType" minOccurs="0" maxOccurs="unbounded">
                <!--Not finding layer ref id-->
                <xs:keyref name="layerIDRef" refer="layerID">
                    <xs:selector xpath="DCELayer"/>
                    <xs:field xpath="@layer_id_ref"/>
                </xs:keyref>
            </xs:element>
        </xs:sequence>                                         
    </xs:complexType>

    <xs:complexType name="InputLayerType">
        <xs:attribute name="input_ref" type="InputRefType" use="required"/>
        <xs:attribute name="usage" type="InputUsageType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="InputRefType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="dem"/>
            <xs:enumeration value="centerline"/>
            <xs:enumeration value="valley_bottom"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="InputUsageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="normalization"/>
            <xs:enumeration value="surface"/>
            <xs:enumeration value="metric_layer"/>
            <xs:enumeration value="denominator"/>
            <xs:enumeration value="numerator"/>
        </xs:restriction>
    </xs:simpleType>

     <xs:complexType name="DCELayerType">
        <xs:sequence>
            <xs:element name="Usage" type="DCELayerUsageType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="CountFields" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CountField" type="CountFieldType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="AttributeFilter" type="AttributeFilterType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="layer_id_ref" type="IdType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="DCELayerUsageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Denominator"/>
            <xs:enumeration value="Numerator"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="CountFieldType">
        <xs:attribute name="field_id_ref" type="IdType" use="required"/>
    </xs:complexType>

    <xs:complexType name="AttributeFilterType">
        <xs:sequence>
            <xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="field_id_ref" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== Riverscapes/RiverscapesXML/QRiS/protocols/tier_1_geounit_protocol.xml
<Protocol machine_code="TIER_1_GEOUNIT" version="1.0" status="experimental" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://xml.riverscapes.net/QRiS/protocol.xsd">
    <Label>Tier 1 Geomorphic Unit Protocol</Label>
    <Description>Tier 1 Geomorphic Unit Assessment of Valley Bottom</Description>
    <URL>https://lowtechpbr.restoration.usu.edu/</URL>
    <Citation> Wheaton J.M., Bennett S.N., Bouwes, N., Maestas J.D. and Shahverdian S.M. (Editors). 2019. Low-Tech Process-Based Restoration of Riverscapes: Design Manual. Version 1.0. Utah State University Restoration Consortium. Logan, UT. 286 pp. DOI: 10.13140/RG.2.2.19590.63049/2.</Citation>
    <Author>Zach Burgert</Author>
    <CreationDate>2025-08-18</CreationDate>
    <UpdatedDate>2025-09-02</UpdatedDate>
    <Layers>
        <Layer id="active_channel_lines" version="1.0" geom_type="Linestring">
            <Label>Active Channel Lines</Label>
            <Symbology>centerlines_tier_1.qml</Symbology>
            <Description>Centerlines of Primary and Non-Primary Channels</Description>
            <Fields>
                <ListField id="channel_type" version="1.0">
                    <Label>Type</Label>
                    <Values>
                        <Value>Primary</Value>
                        <Value>Non-Primary</Value>
                    </Values>
                </ListField>
                <TextField id="notes" version="1.0">
                    <Label>Notes</Label>
                </TextField>
            </Fields>
        </Layer>
            <Layer id="tier_1_geomorphic_unit_extents" version="1.0" geom_type="Polygon">
            <Label>Geomorphic Units</Label>
            <Symbology>tier_1_extents.qml</Symbology>
            <Description>Tier 1 Geomorphic Units Polygon Layer</Description>
            <Fields>
                <ListField id="geo_unit_type" version="1.0">
                    <Label>Type</Label>
                    <Values>
                        <Value>Channel</Value>
                        <Value>Active Floodplain</Value>
                        <Value>Inactive Floodplain</Value>
                        <Value>Terrace</Value>
                        <Value>Alluvial Fan</Value>
                        <Value>Colluvial Fan</Value>
                        <Value>Moraine</Value>
                        <Value>Hillslope/Upland</Value>
                    </Values>
                </ListField>
                <TextField id="notes" version="1.0">
                    <Label>Notes</Label>
                </TextField>
            </Fields>
        </Layer>
        <Layer id="margins" version="1.0" geom_type="Linestring">
            <Label>Margins</Label>
            <Symbology>margins.qml</Symbology>
            <Description>Margins of the Valley, Valley Bottom, and Active Channel</Description>
            <Fields>
                <ListField id="tier_1_margin_type" version="1.0">
                    <Label>Tier 1 Type</Label>
                    <Values>
                        <Value>Channel Margin</Value>
                        <Value>Valley Bottom Margin</Value>
                        <Value>Valley Margin</Value>
                    </Values>
                </ListField>
                <ListField id="margin_origin" version="1.0">
                    <Label>Origin</Label>
                    <Values>
                        <Value>Anthropogenic</Value>
                        <Value>Natural</Value>
                        <Value>Natural and Anthropogenic</Value>
                    </Values>
                </ListField>
                <ListField id="tier_2_margin_type" version="1.0">
                    <Label>Tier 2 Type</Label>
                    <Values>
                        <Value>Embankment</Value>
                        <Value>Fence</Value>
                        <Value>Hedgerow</Value>
                        <Value>Constructed Levee</Value>
                        <Value>Railroad</Value>
                        <Value>Road</Value>
                        <Value>Wall</Value>
                    </Values>
                </ListField>
                <ListField id="availability" version="1.0">
                    <Label>Available Sediment, Wood, or Vegetation</Label>
                    <Values>
                        <Value>Yes</Value>
                        <Value>No</Value>
                    </Values>
                </ListField>
                <TextField id="notes" version="1.0">
                    <Label>Notes</Label>
                </TextField>
            </Fields>
        </Layer>
        <Layer id="confining_margins" version="1.0" geom_type="Linestring">
            <Label>Confining Margins</Label>
            <Symbology>confining_margins.qml</Symbology>
            <Description>Confining Margins of the Active Channel</Description>
            <Fields>
                <ListField id="confinement_type" version="1.0">
                    <Label>Confinement Type</Label>
                    <Values>
                        <Value>Left</Value>
                        <Value>Right</Value>
                        <Value>Both</Value>
                    </Values>
                </ListField>
                <TextField id="notes" version="1.0">
                    <Label>Notes</Label>
                </TextField>
            </Fields>
        </Layer>
    </Layers>
    <Metrics>
        <Metric id="confining_margin_length" version="1.0" calculation_machine_code="length">
            <Label>Total Length of Confining Margins</Label>
            <DefaultLevel>Metric</DefaultLevel>
            <MinimumValue>0</MinimumValue>
            <Precision>2</Precision>
            <Parameters>
                <DCELayer layer_id_ref="confining_margins">
                </DCELayer>
            </Parameters>
        </Metric>
        <Metric id="active_channel_proportion" version="1.0" calculation_machine_code="area_proportion">
            <Label>Active Channel Proportion</Label>
            <DefaultLevel>Metric</DefaultLevel>
            <Description>Proportion of Active Channel within Valley Bottom of Each Sample Frame</Description>
            <DefinitionURL/>
            <MinimumValue>0</MinimumValue>
            <Precision>2</Precision>
            <Parameters>
                <DCELayer layer_id_ref="tier_1_geomorphic_unit_extents">
                    <Usage>Numerator</Usage>
                    <AttributeFilter field_id_ref="geo_unit_type">
                        <Value>Channel</Value>
                    </AttributeFilter>
                </DCELayer>
            </Parameters>
        </Metric> 
        <Metric id="active_floodplain_proportion" version="1.0" calculation_machine_code="area_proportion">
            <Label>Active Floodplain Proportion</Label>
            <DefaultLevel>Metric</DefaultLevel>
            <Description>Proportion of Active Floodplain within Valley Bottom of Each Sample Frame</Description>
            <DefinitionURL/>
            <MinimumValue>0</MinimumValue>
            <Precision>2</Precision>
            <Parameters>
                <DCELayer layer_id_ref="tier_1_geomorphic_unit_extents">
                    <Usage>Numerator</Usage>
                    <AttributeFilter field_id_ref="geo_unit_type">
                        <Value>Active Floodplain</Value>
                    </AttributeFilter>
                </DCELayer>
            </Parameters>
        </Metric>
        <Metric id="inactive_floodplain_proportion" version="1.0" calculation_machine_code="area_proportion">
            <Label>Inactive Floodplain Proportion</Label>
            <DefaultLevel>Metric</DefaultLevel>
            <Description>Proportion of Inactive Floodplain within Valley Bottom of Each Sample Frame</Description>
            <DefinitionURL/>
            <MinimumValue>0</MinimumValue>
            <Precision>2</Precision>
            <Parameters>
                <DCELayer layer_id_ref="tier_1_geomorphic_unit_extents">
                    <Usage>Numerator</Usage>
                    <AttributeFilter field_id_ref="geo_unit_type">
                        <Value>Inactive Floodplain</Value>
                    </AttributeFilter>
                </DCELayer>
            </Parameters>
        </Metric>
    </Metrics>
</Protocol>
