=== Riverscapes/RiverscapesXML/QRiS/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    attributeFormDefault="unqualified" 
    elementFormDefault="qualified" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Top Level Protocol Schema -->
    <xs:element name="Protocol">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Citation" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Author" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="CreationDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="UpdatedDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element type="MetaDataType" name="MetaData" minOccurs="0" maxOccurs="1">
                    <xs:unique name="UniqueMetadataKeys">
                        <xs:selector xpath="./Meta" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
                <xs:element name="Layers" type="LayersType" minOccurs="1" maxOccurs="1">
                    <xs:key name="layerID">
                        <xs:selector xpath="Layer"/>
                        <xs:field xpath="@id"/>
                    </xs:key>
                </xs:element>
                <xs:element name="Metrics" type="MetricsType" minOccurs="0" maxOccurs="1">
                    <xs:unique name="UniqueMetricIDVersion">
                        <xs:selector xpath="Metric"/>
                        <xs:field xpath="@id"/>
                        <xs:field xpath="@version"/>
                        <xs:field xpath="@status"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="machine_code" type="MachineCodeType" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="status" type="ProtocolStatusType" use="required"/>
            <xs:attribute name="protocol_type" type="ProtocolTypeType" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Generic Types -->
    <xs:simpleType name="IdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z][a-zA-Z0-9_]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MachineCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z0-9_]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ValuesType">
        <xs:sequence>
            <xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MetaType">
        <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="name" use="required" />
            <xs:attribute type="MetaKeyValueType" name="type" use="optional" />
            <xs:attribute type="xs:boolean" name="locked" use="optional" />
            <xs:attribute type="MetaKeySrcType" name="ext" use="optional" />
        </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

  <xs:complexType name="MetaDataType">
    <xs:sequence>
      <xs:element type="MetaType" name="Meta" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

    <!-- The type of string in the <Meta> tag. These are optional -->
    <xs:simpleType name="MetaKeyValueType">
        <xs:restriction base="xs:string">
        <xs:enumeration value="guid" />
        <xs:enumeration value="url" />
        <xs:enumeration value="filepath" />
        <xs:enumeration value="image" />
        <xs:enumeration value="video" />
        <xs:enumeration value="isodate" />
        <xs:enumeration value="timestamp" />
        <xs:enumeration value="float" />
        <xs:enumeration value="boolean" />
        <xs:enumeration value="int" />
        <xs:enumeration value="richtext" />
        <xs:enumeration value="markdown" />
        <xs:enumeration value="json" />
        <!-- Hidden just means this is rarely useful to humans so never render it directly 
                (it's not secret or private)
        -->
        <xs:enumeration value="hidden" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MetaKeySrcType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="warehouse" />
            <xs:enumeration value="project" />
            <xs:enumeration value="dataset" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GeomType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Point"/>
            <xs:enumeration value="Linestring"/>
            <xs:enumeration value="Polygon"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ProtocolStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="experimental"/>
            <xs:enumeration value="production"/>
            <xs:enumeration value="deprecated"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ProtocolTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="asbuilt"/>
            <xs:enumeration value="design"/>
            <xs:enumeration value="dce"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Layer Types -->
    <xs:complexType name="LayersType">
        <xs:sequence>
            <xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LayerType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Symbology" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MenuItems" type="MenuItemsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Hierarchy" type="HierarchyItemsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Fields" type="LayerFieldsType" minOccurs="0" maxOccurs="1">
                <xs:unique name="uniqueFieldID">
                    <xs:selector xpath="*"/>
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>
            <xs:element type="MetaDataType" name="MetaData" minOccurs="0" maxOccurs="1">
                <xs:unique name="UniqueLayerMetadataKeys">
                    <xs:selector xpath="./Meta" />
                    <xs:field xpath="@name" />
                </xs:unique>
            </xs:element>
        </xs:all>
        <xs:attribute name="id" type="IdType" use="required"/>
        <xs:attribute name="version" type="xs:string" use="required"/>
        <xs:attribute name="geom_type" type="GeomType" use="required"/>
    </xs:complexType>

    <xs:complexType name="MenuItemsType">
        <xs:sequence>
            <xs:element name="MenuItem" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HierarchyItemsType">
        <xs:sequence>
            <xs:element name="HierarchyItem" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LayerFieldsType">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="IntegerField" type="IntegerFieldType"/>
                <xs:element name="FloatField" type="FloatFieldType"/>
                <xs:element name="TextField" type="TextFieldType"/>
                <xs:element name="ListField" type="ListFieldType"/>
                <xs:element name="AttachmentField" type="AttachmentFieldType"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!-- Field Types -->

    <xs:attributeGroup name="BaseFieldAttributes">
        <xs:attribute name="id" type="IdType" use="required"/>
        <xs:attribute name="version" type="xs:string" use="required"/>
        <xs:attribute name="value_required" type="xs:boolean" default="false" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="IntegerFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MinimumValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaximumValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Slider" type="IntegerSliderType" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <xs:complexType name="FloatFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MinimumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaximumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Precision" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Slider" type="FloatSliderType" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <xs:complexType name="IntegerSliderType">
        <xs:attribute name="min" type="xs:integer" use="required"/>
        <xs:attribute name="max" type="xs:integer" use="required"/>
        <xs:attribute name="step" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:complexType name="FloatSliderType">
        <xs:attribute name="min" type="xs:float" use="required"/>
        <xs:attribute name="max" type="xs:float" use="required"/>
        <xs:attribute name="step" type="xs:float" use="required"/>    
    </xs:complexType>

    <!-- Derived Text Field Type -->
    <xs:complexType name="TextFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaxLength" type="xs:integer" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <!-- Derived Attachment Field Type -->
    <xs:complexType name="AttachmentFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaxAttachments" type="xs:integer" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <!-- Derived List Field Type -->
    <xs:complexType name="ListFieldType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Visibility" type="VisibilityType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Values" type="ListValuesType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DerivedValues" type="DerivedValuesType" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attributeGroup ref="BaseFieldAttributes"/>
    </xs:complexType>

    <!-- extend values type to include custom values attribute-->
    <xs:complexType name="ListValuesType">
        <xs:complexContent>
            <xs:extension base="ValuesType">
                <xs:attribute name="allow_custom_values" type="xs:boolean" default="false" use="optional"/>
                <xs:attribute name="allow_multiple_values" type="xs:boolean" default="false" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DerivedValuesType">
        <xs:sequence>
            <xs:element name="DerivedValue" type="DerivedValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DerivedValueType">
        <xs:sequence>
            <xs:element name="InputValue" type="InputValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="output" type="xs:string" use="required"/>
    </xs:complexType>
            
    <xs:complexType name="InputValueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="field_id_ref" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="VisibilityType">
        <xs:sequence>
            <xs:element name="Values" type="ValuesType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="field_id_ref" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Metric Types -->
    <xs:complexType name="MetricsType">
        <xs:sequence>
            <xs:element name="Metric" type="MetricType" minOccurs="1" maxOccurs="unbounded">
                <xs:unique name="uniqueMetricID">
                    <xs:selector xpath="*"/>
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MetricType">
        <xs:all>
            <xs:element name="Label" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="DefaultLevel" type="MetricLevelType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="DefinitionURL" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Hierarchy" type="HierarchyItemsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MinimumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="MaximumValue" type="xs:float" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Precision" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Parameters" type="MetricParametersType" minOccurs="0" maxOccurs="1">
            </xs:element>
        </xs:all>
        <xs:attribute name="id" type="IdType" use="required"/>
        <xs:attribute name="version" type="xs:string" use="required"/>
        <xs:attribute name="calculation_machine_code" type="xs:string" use="required"/>
        <xs:attribute name="status" type="MetricStatusType" default="active"/>
    </xs:complexType>

    <xs:simpleType name="MetricStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deprecated"/>
            <xs:enumeration value="experimental"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MetricLevelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Metric"/>
            <xs:enumeration value="Indicator"/>
            <xs:enumeration value="None"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="MetricParametersType">
        <xs:sequence>
            <xs:element name="InputLayer" type="InputLayerType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="DCELayer" type="DCELayerType" minOccurs="0" maxOccurs="unbounded">
                <!--Not finding layer ref id-->
                <xs:keyref name="layerIDRef" refer="layerID">
                    <xs:selector xpath="DCELayer"/>
                    <xs:field xpath="@layer_id_ref"/>
                </xs:keyref>
            </xs:element>
        </xs:sequence>                                         
    </xs:complexType>

    <xs:complexType name="InputLayerType">
        <xs:attribute name="input_ref" type="InputRefType" use="required"/>
        <xs:attribute name="usage" type="InputUsageType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="InputRefType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="dem"/>
            <xs:enumeration value="centerline"/>
            <xs:enumeration value="valley_bottom"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="InputUsageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="normalization"/>
            <xs:enumeration value="surface"/>
            <xs:enumeration value="metric_layer"/>
            <xs:enumeration value="denominator"/>
            <xs:enumeration value="numerator"/>
        </xs:restriction>
    </xs:simpleType>

     <xs:complexType name="DCELayerType">
        <xs:sequence>
            <xs:element name="Usage" type="DCELayerUsageType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="CountFields" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CountField" type="CountFieldType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="AttributeFilter" type="AttributeFilterType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="layer_id_ref" type="IdType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="DCELayerUsageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Denominator"/>
            <xs:enumeration value="Numerator"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="CountFieldType">
        <xs:attribute name="field_id_ref" type="IdType" use="required"/>
    </xs:complexType>

    <xs:complexType name="AttributeFilterType">
        <xs:sequence>
            <xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="field_id_ref" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== Riverscapes/RiverscapesXML/QRiS/protocols/beaver_census_protocol.xml
<Protocol machine_code="BEAVER_CENSUS" version="1.0" status="production" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://xml.riverscapes.net/QRiS/protocol.xsd">
    <Label>Beaver Census Protocol</Label>
    <Description>Beaver Census Layers</Description>
    <URL>https://lowtechpbr.restoration.usu.edu/</URL>
    <Citation> Wheaton J.M., Bennett S.N., Bouwes, N., Maestas J.D. and Shahverdian S.M. (Editors). 2019. Low-Tech Process-Based Restoration of Riverscapes: Design Manual. Version 1.0. Utah State University Restoration Consortium. Logan, UT. 286 pp. DOI: 10.13140/RG.2.2.19590.63049/2.</Citation>
    <Author>Jordan Gilbert</Author>
    <CreationDate>2024-09-01</CreationDate>
    <UpdatedDate>2024-09-01</UpdatedDate>
    <Layers>
        <Layer id="beaver_dam" version="1.0" geom_type="Point">
            <Label>Beaver Dam</Label>
            <Symbology>beaver_dam.qml</Symbology>
            <Description>Beaver Dam Layer</Description>
            <Hierarchy>
                <HierarchyItem>Observations</HierarchyItem>
                <HierarchyItem>Beaver Activity</HierarchyItem>
            </Hierarchy>
            <Fields>
                <ListField id="dam_cer" version="1.0">
                    <Label>Dam CER</Label>
                    <DefaultValue>high</DefaultValue>
                    <Values>
                        <Value>high</Value>
                        <Value>medium</Value>
                        <Value>low</Value>
                    </Values>
                </ListField>
                <ListField id="dam_type" version="1.0">
                    <Label>Dam Type</Label>
                    <DefaultValue>active_dam</DefaultValue>
                    <Values>
                        <Value>active_dam</Value>
                        <Value>inactive_dam</Value>
                        <Value>relic_dam</Value>
                        <Value>uncertain</Value>
                    </Values>
                </ListField>
            </Fields>
        </Layer>
        <Layer id="beaver_sign" version="1.0" geom_type="Point">
            <Label>Beaver Sign</Label>
            <Symbology>beaver_sign.qml</Symbology>
            <Description>Beaver Sign Layer</Description>
            <Hierarchy>
                <HierarchyItem>Observations</HierarchyItem>
                <HierarchyItem>Beaver Activity</HierarchyItem>
            </Hierarchy>
            <Fields>
                <ListField id="sign_type" version="1.0">
                    <Label>Type</Label>
                    <Values>
                        <Value>bank_den</Value>
                        <Value>bank_lodge</Value>
                        <Value>canal</Value>
                        <Value>chew_stick</Value>
                        <Value>clipped_vegetation</Value>
                        <Value>felled_tree</Value>
                        <Value>food_cache</Value>
                        <Value>harvested_branches</Value>
                        <Value>other</Value>
                        <Value>pond_excavation</Value>
                        <Value>pond_lodge</Value>
                        <Value>scat</Value>
                        <Value>scent_mound</Value>
                        <Value>set_of_tracks</Value>
                        <Value>skid_trail</Value>
                        <Value>slide</Value>
                    </Values>
                </ListField>
            </Fields> 
        </Layer>
    </Layers>
</Protocol>
